### ISSUE TITLE
java.io.FileNotFoundException when saving image

### ISSUE THREAD

**Issue by mscherer82** [hui-z/image_gallery_saver#107]
```
if (await Permission.storage.request().isGranted) {
              Log.d("save image to gallery");
              await ImageGallerySaver.saveImage(result.readAsBytesSync(),
                  quality: 100);
}
```

gives me the follwing error on android:

```
W/System.err(18695): java.io.FileNotFoundException: /storage/emulated/0/Framr/1599469563636.jpg: open failed: ENOENT (No such file or directory)
W/System.err(18695): 	at libcore.io.IoBridge.open(IoBridge.java:496)
W/System.err(18695): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
W/System.err(18695): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
W/System.err(18695): 	at com.example.imagegallerysaver.ImageGallerySaverPlugin.saveImageToGallery(ImageGallerySaverPlugin.kt:64)
W/System.err(18695): 	at com.example.imagegallerysaver.ImageGallerySaverPlugin.onMethodCall(ImageGallerySaverPlugin.kt:36)
W/System.err(18695): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:230)
W/System.err(18695): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
W/System.err(18695): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
W/System.err(18695): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(18695): 	at android.os.MessageQueue.next(MessageQueue.java:336)
W/System.err(18695): 	at android.os.Looper.loop(Looper.java:174)
W/System.err(18695): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
W/System.err(18695): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(18695): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
W/System.err(18695): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
W/System.err(18695): Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
W/System.err(18695): 	at libcore.io.Linux.open(Native Method)
W/System.err(18695): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
W/System.err(18695): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
W/System.err(18695): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
W/System.err(18695): 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7255)
W/System.err(18695): 	at libcore.io.IoBridge.open(IoBridge.java:482)
W/System.err(18695): 	... 14 more

```

**Comment by ngocnpt1999** [comment]
same issues

**Comment by hiedar** [comment]
I encountered same issue, but solved.

My problem is...

```
      child: MaterialApp(
        title: 'Sample App',
```

A space is contained in the title of MaterialApp. Removed the spaces, then solved.

**Comment by hiedar** [comment]
> I encountered same issue, but solved.
> 
> My problem is...
> 
> ```
>       child: MaterialApp(
>         title: 'Sample App',
> ```
> 
> A space is contained in the title of MaterialApp. Removed the spaces, then solved.

Wrong above.
On Android 10, same issue appeared.

And resolved by setting compileSdkVersion in build.gradle to 28.

**Comment by nezoat** [comment]
same issue

**Comment by rogiervandenberg** [comment]
I found a way that fixes it for me. In your `android/app/src/main/AndroidManifest.xml` file, at 

```
<application android:label="APPNAME" android:icon="ICONNAME" ...>
```

add: `android:requestLegacyExternalStorage="true"`, like so:

```
<application android:label="APPNAME" android:icon="ICONNAME" android:requestLegacyExternalStorage="true">
```

It will then use the pre-Android 10 way of requesting access to storage, so you can still save your file as you could earlier.

**Comment by FeifanChang** [comment]
> I found a way that fixes it for me. In your `android/app/src/main/AndroidManifest.xml` file, at
> 
> ```
> <application android:label="APPNAME" android:icon="ICONNAME" ...>
> ```
> 
> add: `android:requestLegacyExternalStorage="true"`, like so:
> 
> ```
> <application android:label="APPNAME" android:icon="ICONNAME" android:requestLegacyExternalStorage="true">
> ```
> 
> It will then use the pre-Android 10 way of requesting access to storage, so you can still save your file as you could earlier.
> 
> _But caution: After you update your app to target Android 11 (API level 30), the system ignores the requestLegacyExternalStorage attribute when your app is running on Android 11 devices, so your app must be ready to support scoped storage and to migrate app data for users on those devices. See https://developer.android.com/training/data-storage/use-cases#opt-out-scoped-storage for more info_

it works for me !! thanks a lot!
