### ISSUE TITLE
Target SDK: 29 not compatible

### ISSUE THREAD

**Issue by kingdg25** [hui-z/image_gallery_saver#111]
Can't download/save image to gallery with `targetSdkVersion 29`
```[✓] Flutter (Channel stable, v1.12.13+hotfix.7, on Linux, locale en_US.utf8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Android Studio (version 3.5)
[!] VS Code (version 1.37.0)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)```

It only works when i changed back to targetSdkVersion to 28

**Comment by hunter2009pf** [comment]
If you are developing your app with android 10, you may encounter this problem.
To solve this, you need to modify your AndroidManifest.xml like this:
<application
        android:name="io.flutter.app.FlutterApplication"
        android:label="hello"
        android:icon="@mipmap/app_icon"
        android:requestLegacyExternalStorage="true">

adding android:requestLegacyExternalStorage will resolve this problem.

**Comment by kingdg25** [comment]
Wow thanks @hunter2009pf ! It worked !
I also found it out here. 
https://developer.android.com/training/data-storage/use-cases#opt-out-scoped-storage
