### ISSUE TITLE
open failed: EACCES (Permission denied)

### ISSUE THREAD

**Issue by maxiao1015** [hui-z/image_gallery_saver#112]
In Android 29 version, the prompt does not have the permission, but actually has the permission

**Comment by marcobraghim** [comment]
You can easily solve it by installing the package **permission_handler**

https://pub.dev/packages/permission_handler

**Comment by frostextreme11** [comment]
hi @marcobraghim I already add the permission_handler but the issue still persists.

**Comment by marcobraghim** [comment]
> hi @marcobraghim I already add the **permission_handler** but the issue still persists.
> any other suggestions?

Could you share your code?

**Comment by frostextreme11** [comment]
> 
> 
> > hi @marcobraghim I already add the **permission_handler** but the issue still persists.
> > any other suggestions?
> 
> Could you share your code?

here is the code.

`_save() async {
    if (Platform.isAndroid) {
      await _askPermission();
    }
    _onLoading(context);
    var response = await Dio().get(widget.imageAddress,
        options: Options(responseType: ResponseType.bytes));
    final result =
        await ImageGallerySaver.saveImage(Uint8List.fromList(response.data));
    print(result);

    SuccessDialog("Wallpaper Downloaded To Your Gallery", context);
  }`

`_askPermission() async {
    if (Platform.isIOS) {
      //Map<Permission, PermissionStatus> permissions = await PermissionHandler();
    } else {
      PermissionStatus permission = await Permission.storage.request();
      print(permission);
      if (await Permission.storage.request().isGranted) {
        print("permission granted!");
      }
    }
  }`

**Comment by frostextreme11** [comment]
> 
> 
> > hi @marcobraghim I already add the **permission_handler** but the issue still persists.
> > any other suggestions?
> 
> Could you share your code?

Here is the code:
```
_askPermission() async {
    if (Platform.isIOS) {
      //Map<Permission, PermissionStatus> permissions = await PermissionHandler();
    } else {
      PermissionStatus permission = await Permission.storage.request();
      print(permission);
      if (await Permission.storage.request().isGranted) {
        print("permission granted!");
      }
    }
  }
```
```
_save() async {
    if (Platform.isAndroid) {
      await _askPermission();
    }
    _onLoading(context);
    var response = await Dio().get(widget.imageAddress,
        options: Options(responseType: ResponseType.bytes));
    final result =
        await ImageGallerySaver.saveImage(Uint8List.fromList(response.data));
    print(result);

    SuccessDialog("Wallpaper Downloaded To Your Gallery", context);
  }
```

**Comment by marcobraghim** [comment]
Try to change the code below
```dart
PermissionStatus permission = await Permission.storage.request();
print(permission);
if (await Permission.storage.request().isGranted) {
   print("permission granted!");
}
```

By this code:
```dart
PermissionStatus permission = await Permission.storage.request();

if (permission == PermissionStatus.granted) {
   print("permission granted!");

    // Try to save your image as file instead
    await ImageGallerySaver.saveFile(path);
}
```

May I be wrong, but seems to me that your issue is more related to logic than the package itself.. Did you installed the package correctly? Are you sure?

**Comment by frostextreme11** [comment]
using the `ImageGallerySaver.saveFile(path)` is working for downloading the image now.

here is the code: 
```
      var appDocDir = await getExternalStorageDirectory();
      String savePath = appDocDir.path + "/image_name.jpg";
      String fileUrl = widget.imageAddress;
      await Dio().download(fileUrl, savePath);
      final result = await ImageGallerySaver.saveFile(savePath);
      print(result);
      print(savePath);
```
thank you @marcobraghim

**Comment by varunkumarmedam** [comment]
If your tagetedSdk version is 29 or greater see this [thread](https://github.com/hui-z/image_gallery_saver/issues/111)

**Comment by websprinkles** [comment]
I've noticed that permission is denied when your app name (as it looks to me, this library uses it as the default folder where the image gets saved?) contains multiple words... 
/storage/emulated/0/myapp/16081994555555.jpg works OK, while /storage/emulated/0/my app: hello world/16081994555555.jpg does not.
