### ISSUE TITLE
Android10保存图片失败

### ISSUE THREAD

**Issue by PaIn22152** [hui-z/image_gallery_saver#118]
作者你好，在android10手机上，保存图片失败（手机型号一加8pro），后续手机系统升级到android11，保存图片依然失败

**Comment by PaIn22152** [comment]
在android9的设备上，可以正常使用

**Comment by canitez** [comment]
Yes this problem exists on android 10. How to fix it. It works normally at 9.

**Comment by pdqk** [comment]
Hi there. I just want to know why image was saved to gallery is terrible because of i set its quality = 100? Anyone can help... Sorry about my english.

**Comment by xqqlv** [comment]
#63
