### ISSUE TITLE
saveImage will not return when user only allow selected access to Gallery

### ISSUE THREAD

**Issue by crystalztl** [hui-z/image_gallery_saver#126]
The implementation for retrieving image location string in iOS is not ideal for iOS 14 users.

It will asking unnecessary permission and in iOS14 users have choice to only allow selected access. In this scenario, the function will not return correct string and we cannot know whether the saving is successful.

Asking unnecessary permission also looks wired. I think we'd better to revert to 1.5.0, and let application level handle the platform differences.

```
     final bool saveSuccess = Platform.isIOS
          ? result is bool && result == true
          : result is String && result != '';
```

**Comment by xqqlv** [comment]
next version, i will return a map as "{"isSuccess":true, "filePath":String?}"，developer can selete save method

**Comment by crystalztl** [comment]
Thanks for prompt reply. is there a save mode which don't need the extra permission if developer don't need the filePath?
