### ISSUE TITLE
更新过后，安卓保存图片失败

### ISSUE THREAD

**Issue by Taonanqiang** [hui-z/image_gallery_saver#128]
因为IOS之前读取权限闪退，更新后，ios可以保存， 但是安卓不行了，安卓用的是storage，ios用的是photo，但是安卓的saveImage没有返回东西，还说权限被拒绝了
![image](https://user-images.githubusercontent.com/53744767/98520439-0136fe80-22ad-11eb-8cbb-2d0b4d51b894.png)

**Comment by mulieli** [comment]
相同的问题 请问是否已经解决了呢 我的是华为手机有问题。 其他的机型还没遇到这个问题

**Comment by xqqlv** [comment]
#63

**Comment by Taonanqiang** [comment]
> 相同的问题 请问是否已经解决了呢 我的是华为手机有问题。 其他的机型还没遇到这个问题

**Comment by Taonanqiang** [comment]
> 相同的问题 请问是否已经解决了呢 我的是华为手机有问题。 其他的机型还没遇到这个问题

好了，在AndroidManifest.xml文件中加一句话，android:requestLegacyExternalStorage = "true"
