### ISSUE TITLE
Failed to handle method call

### ISSUE THREAD

**Issue by HatsuneMikuV** [hui-z/image_gallery_saver#131]
java.lang.ClassCastException: java.util.HashMap cannot be cast to java.lang.String
E/MethodChannel#image_gallery_saver( 1123): 	at com.example.imagegallerysaver.ImageGallerySaverPlugin.onMethodCall(ImageGallerySaverPlugin.kt:39)
E/MethodChannel#image_gallery_saver( 1123): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#image_gallery_saver( 1123): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#image_gallery_saver( 1123): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/MethodChannel#image_gallery_saver( 1123): 	at android.os.MessageQueue.nativePollOnce(Native Method)

**Android**

![AF234D247D2DAC31FB2C775B843AE8A5](https://user-images.githubusercontent.com/14038743/98928106-59bc0500-2514-11eb-9d1a-f6f1055baf7a.jpg)

**iOS**
![DE3A237F0982412DC48847FEFDDEBFA2](https://user-images.githubusercontent.com/14038743/98928136-693b4e00-2514-11eb-925c-25e9070574c7.jpg)

more
![45C18EEB3E0C402BC6E26D9667B1D32A](https://user-images.githubusercontent.com/14038743/98928174-75bfa680-2514-11eb-89fa-ca912244c545.jpg)

**Comment by ArjanAswal** [comment]
I am having the same issue. Any way to solve this?
@HatsuneMikuV Any workarounds to this problem?
