### ISSUE TITLE
华为安卓10保存失败

### ISSUE THREAD

**Issue by mulieli** [hui-z/image_gallery_saver#133]
java.io.FileNotFoundException: /storage/emulated/0/项目名/a3e3586544814100810905da98345f18.jpg: open failed: ENOENT (No such file or directory)

华为手机的型号是mate20

其他手机还没遇到这个问题

源码现在的写法不支持android10

**Comment by xqqlv** [comment]
在manifest file添加
<application android:requestLegacyExternalStorage="true" .....>

**Comment by novas1r1** [comment]
I have the same issue. I added <application android:requestLegacyExternalStorage="true" .....> to manifest but error is still there.

**Comment by AlexanderKozhevin** [comment]
I'm having issue during saving network image. I used demo from official documentation


```
I/flutter (19597): {filePath: null, errorMessage: java.io.FileNotFoundException: /storage/emulated/0/flutter_app4/hello.jpg: open failed: ENOENT (No such file or directory), isSuccess: false}

```

**Comment by lizhuoyuan** [comment]
I also encountered the same problem in andorid11, has anyone solved it?
