### ISSUE TITLE
Error when adding library to a new iOS project. 

### ISSUE THREAD

**Issue by shockoe-hatch** [hui-z/image_gallery_saver#135]
Updated a project to the newer version of this library and was receiving the following error. So I tried created a brand new project and added the library and was receiving the exact same error. I didn't change anything with the new project except adding the library. 

``↳
    /Users/caleb/.pub-cache/hosted/pub.dartlang.org/image_gallery_saver-1.6.5/ios/Classes/SwiftImageGallerySaverPlugin
    .swift:64:33: error: call to method 'saveResult' in closure requires explicit 'self.' to make capture semantics
    explicit
                                    saveResult(isSuccess: true, filePath: urlStr)
                                    ^
                                    self.
    /Users/caleb/.pub-cache/hosted/pub.dartlang.org/image_gallery_saver-1.6.5/ios/Classes/SwiftImageGallerySaverPlugin
    .swift:69:21: error: call to method 'saveResult' in closure requires explicit 'self.' to make capture semantics
    explicit
                        saveResult(isSuccess: false, error: errorMessage)
                        ^
                        self.
    /Users/caleb/.pub-cache/hosted/pub.dartlang.org/image_gallery_saver-1.6.5/ios/Classes/SwiftImageGallerySaverPlugin
    .swift:69:57: error: reference to property 'errorMessage' in closure requires explicit 'self.' to make capture
    semantics explicit
                        saveResult(isSuccess: false, error: errorMessage)
                                                            ^
                                                            self.
    /Users/caleb/.pub-cache/hosted/pub.dartlang.org/image_gallery_saver-1.6.5/ios/Classes/SwiftImageGallerySaverPlugin
    .swift:56:42: warning: capture 'self' was never used
            }, completionHandler: { [unowned self] (success, error) in
                                             ^
    /Users/caleb/.pub-cache/hosted/pub.dartlang.org/image_gallery_saver-1.6.5/ios/Classes/SwiftImageGallerySaverPlugin
    .swift:99:33: error: call to method 'saveResult' in closure requires explicit 'self.' to make capture semantics
    explicit
                                    saveResult(isSuccess: true, filePath: urlStr)
                                    ^
                                    self.
    /Users/caleb/.pub-cache/hosted/pub.dartlang.org/image_gallery_saver-1.6.5/ios/Classes/SwiftImageGallerySaverPlugin
    .swift:104:21: error: call to method 'saveResult' in closure requires explicit 'self.' to make capture semantics
    explicit
                        saveResult(isSuccess: false, error: errorMessage)
                        ^
                        self.
    /Users/caleb/.pub-cache/hosted/pub.dartlang.org/image_gallery_saver-1.6.5/ios/Classes/SwiftImageGallerySaverPlugin
    .swift:104:57: error: reference to property 'errorMessage' in closure requires explicit 'self.' to make capture
    semantics explicit
                        saveResult(isSuccess: false, error: errorMessage)
                                                            ^
                                                            self.
    /Users/caleb/.pub-cache/hosted/pub.dartlang.org/image_gallery_saver-1.6.5/ios/Classes/SwiftImageGallerySaverPlugin
    .swift:97:89: warning: capture 'self' was never used
                            imageAsset.requestContentEditingInput(with: options) { [unowned self]
                            (contentEditingInput, info) in
                                                                                            ^
    /Users/caleb/.pub-cache/hosted/pub.dartlang.org/image_gallery_saver-1.6.5/ios/Classes/SwiftImageGallerySaverPlugin
    .swift:136:33: error: call to method 'saveResult' in closure requires explicit 'self.' to make capture semantics
    explicit
                                    saveResult(isSuccess: true, filePath: urlStr)
                                    ^
                                    self.
    /Users/caleb/.pub-cache/hosted/pub.dartlang.org/image_gallery_saver-1.6.5/ios/Classes/SwiftImageGallerySaverPlugin
    .swift:141:21: error: call to method 'saveResult' in closure requires explicit 'self.' to make capture semantics
    explicit
                        saveResult(isSuccess: false, error: errorMessage)
                        ^
                        self.
    /Users/caleb/.pub-cache/hosted/pub.dartlang.org/image_gallery_saver-1.6.5/ios/Classes/SwiftImageGallerySaverPlugin
    .swift:141:57: error: reference to property 'errorMessage' in closure requires explicit 'self.' to make capture
    semantics explicit
                        saveResult(isSuccess: false, error: errorMessage)
                                                            ^
                                                            self.
    /Users/caleb/.pub-cache/hosted/pub.dartlang.org/image_gallery_saver-1.6.5/ios/Classes/SwiftImageGallerySaverPlugin
    .swift:134:89: warning: capture 'self' was never used
                            imageAsset.requestContentEditingInput(with: options) { [unowned self]
                            (contentEditingInput, info) in
                                                                                            ^
    note: Using new build system
    note: Planning build
    note: Constructing build description
``

**Comment by kulture-rob** [comment]
Still getting this in my codemagic cicd with 1.6.6
