### ISSUE TITLE
IOS 高版本XCode打包报错

### ISSUE THREAD

**Issue by mulieli** [hui-z/image_gallery_saver#137]
![image](https://user-images.githubusercontent.com/24307960/100055465-db8a2780-2e5e-11eb-91d4-47c562c8413a.png)
我在打包的时候报以上错误 
语法应该有问题？
在XCode 12版本上？

![image](https://user-images.githubusercontent.com/24307960/100055606-05dbe500-2e5f-11eb-8ec2-c1c3166cdd81.png)

**Comment by xqqlv** [comment]
xcode 12.3?

**Comment by xqqlv** [comment]
你可以提个pr，我帮你合下，我这边还没时间升级

**Comment by mulieli** [comment]
> 你可以提个pr，我帮你合下，我这边还没时间升级

好的 应该是12.2

**Comment by mulieli** [comment]
@xqqlv 创建不了新的pr 需要两个不同的分支

**Comment by zhanghsgithub** [comment]
这问题解决了吗？

**Comment by mulieli** [comment]
> 这问题解决了吗？

暂时没有 需要自己修改本地文件
