### ISSUE TITLE
android11 java.io.FileNotFoundException

### ISSUE THREAD

**Issue by lizhuoyuan** [hui-z/image_gallery_saver#143]
I/flutter (12899): res:{filePath: null, errorMessage: java.io.FileNotFoundException: /storage/emulated/0/flutter_study/1608880712119.jpg: open failed: EPERM (Operation not permitted), isSuccess: false}

目标sdk ： 30
试过在manifest中添加标签 
加了相关权限的请求
最后错误依旧

**Comment by bitores** [comment]
android 10 sdk29 同上

**Comment by bitores** [comment]
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />

I solved this problem by adding permissions
@lizhuoyuan

**Comment by chainchelliah** [comment]
Hey All, I'm also facing this issue. Any solution?
@bitores  I dont understand why it requires Location permissions?

**Comment by lizhuoyuan** [comment]
@bitores bio 
你是复制错内容了吧。。。 
为什么是添加位置权限就ok

**Comment by chainchelliah** [comment]
I had to downgrade the target sdk version form 30 to 29. 
Hope, the team will find a solution for API 30 (Android 11 scoped storage).

**Comment by hunter2009pf** [comment]
If you are running in Android 29 or higher version
you have to use scoped storage or for now, you can bypass this issue by using:

android:requestLegacyExternalStorage="true" 
as one attribute of <Application/> in AndroidManifest.xml

**Comment by lizhuoyuan** [comment]
@hunter2009pf  Only valid in 29

**Comment by 616151371** [comment]
> @ hunter2009pf 仅在29中有效

修改哪个29

**Comment by lizhuoyuan** [comment]
> > @ hunter2009pf 仅在29中有效
> 
> 修改哪个29

目标sdk版本啊

**Comment by Harsh4598** [comment]
> I/flutter (12899): res:{filePath: null, errorMessage: java.io.FileNotFoundException: /storage/emulated/0/flutter_study/1608880712119.jpg: open failed: EPERM (Operation not permitted), isSuccess: false}
> 
> 目标sdk ： 30
> 试过在manifest中添加标签
> 加了相关权限的请求
> 最后错误依旧

I face this only for the first time, then it saves images properly.

**Comment by qiuxiang** [comment]
从 android 11 开始原来的 `WRITE_EXTERNAL_STORAGE` 权限变成 `仅允许访问媒体文件`，也就是说，如果只往 `Pictures`、`DCIM` 目录写文件的话是允许的，可是这个库却没有按照规范在根目录另建文件夹存储，在 android 11 以后是不允许的。

解决的办法很简单，就是这个库不要在根目录新建目录，或者要新建也是在 `Pictures` 目录新建，然后文件写入到 `Pictures` 下，我自己就是这么做的，参考 PR #149

当然，在不改动库的情况下仍然是有两个解决方法：
1. 就像上面提到的，改 target 到 28，或者 29 再加 `android:requestLegacyExternalStorage="true"` 就行了
2. 如果一定要 target 30，那么需要用新权限 `MANAGE_EXTERNAL_STORAGE`，这个权限可以让 android 11 也可以像之前一样往任何目录写文件
