### ISSUE TITLE
targetSdkVersion 30 not compatible

### ISSUE THREAD

**Issue by Akiat** [hui-z/image_gallery_saver#144]
I tried to upgrade my targetSdkVersion to 30 and the image_gallery_saver doesn't work anymore, even with `android:requestLegacyExternalStorage="true"`

```
{filePath: null, errorMessage: java.io.FileNotFoundException: /storage/emulated/0/AppName/1610122071724.jpg: open failed: EPERM (Operation not permitted), isSuccess: false}
```

Downgraded to SDK 29 and everything is fine, even without `android:requestLegacyExternalStorage="true"`.

**Comment by JAICHANGPARK** [comment]
I had same problem 

 `{filePath: null, errorMessage: java.io.FileNotFoundException: /storage/emulated/0/flutter_creator/2021-01-10 11:58:05.jpg: open failed: ENOENT (No such file or directory), isSuccess: false}`

**Comment by houdayec** [comment]
@JAICHANGPARK @Akiat did you guys find a solution?

**Comment by JAICHANGPARK** [comment]
@houdayec I think it occurred only emulator

**Comment by houdayec** [comment]
@JAICHANGPARK Great to know, I'll see. Thanks for your answer.

**Comment by karabanovbs** [comment]
I had same problem with pixel 3a.

**Comment by lan2000** [comment]
I also reported an error on an Android 11 device.
Do you have a solution, thank you.

**Comment by SirusCodes** [comment]
Android 11 will ignore `android:requestLegacyExternalStorage=true` you can see that [here](https://developer.android.com/about/versions/11/privacy/storage) we need to use [Scoped Storage](https://developer.android.com/training/data-storage#scoped-storage)

**Comment by ahmetbayirli** [comment]
I have to stay on targetSdkVersion 30 because of some other dependencies. GalerySaver gives built error, saying  Type mismatch: inferred type is String? but String was expected ..... Execution failed for task ':gallery_saver:compileDebugKotlin'
I have tried flutter clean, run, pug cache clear etc.
