### ISSUE TITLE
在安卓手机上保存不了图片和视频为什么呢？

### ISSUE THREAD

**Issue by 616151371** [hui-z/image_gallery_saver#145]
{filePath: null, errorMessage: java.io.FileNotFoundException: /storage/emulated/0/sifan/1611216613838.jpg: open failed: ENOENT (No such file or directory), isSuccess: false}  求解

**Comment by wengxianxun** [comment]
同样到问题，权限也加了

**Comment by sleepreading** [comment]
你搜遍了网络, 很多人会让你加上: android:requestLegacyExternalStorage="true", 以便适配Android10
但是实际上并不起效果.

还必须如作者的demo一样: 引入(必须!!) **permission_handler** 插件, 并添加代码:

`  _requestPermission() async {
    Map<Permission, PermissionStatus> statuses = await [
       Permission.storage,
    ].request();

    final info = statuses[Permission.storage].toString();
    print(info);
  }
`

不要再浪费时间了. 我浪费了个把小时搜索, 作者也不说清楚!

**Comment by sleepreading** [comment]
对了
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>

**Comment by sleepreading** [comment]
对了, 下面的添加并无效果(不要再浪费时间了):
```
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
```

**Comment by 616151371** [comment]
> 你搜遍了网络, 很多人会让你加上: android:requestLegacyExternalStorage="true", 以便适配Android10
> 但是实际上并不起效果.
> 
> 还必须如作者的demo一样: 引入(必须!!) **permission_handler** 插件, 并添加代码:
> 
> ```
>   _requestPermission() async {
>     Map<Permission, PermissionStatus> statuses = await [
>        Permission.storage,
>     ].request();
> 
>     final info = statuses[Permission.storage].toString();
>     print(info);
>   }
> ```
> 
> 不要再浪费时间了. 我浪费了个把小时搜索, 作者也不说清楚!



> 对了, 下面的添加并无效果(不要再浪费时间了):
> 
> ```
>     <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
>     <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
> ```

是的，我最终也是用了permission_handler插件。调用权限完成
