### ISSUE TITLE
工程报错

### ISSUE THREAD

**Issue by ZW19920614** [hui-z/image_gallery_saver#15]
Definition of 'ImageGallerySaverPlugin' must be imported from module 'image_gallery_saver.ImageGallerySaverPlugin' before it is requir

**Comment by hyjfine** [comment]
能把出错环境和详细日志贴一下嘛？

**Comment by ZW19920614** [comment]
就是这个库引入iOS报错[](url)
![8AB1F296-E0E6-4ECD-BC7C-9F9674BDBA06](https://user-images.githubusercontent.com/24447161/54893778-5369b700-4ef2-11e9-97ea-90b645acaac6.png)

**Comment by xqqlv** [comment]
你不是flutter项目？只是oc引用flutter吗？

**Comment by xqqlv** [comment]
oc工程引用swift要在podfile文件中添加use_frameworks!
