### ISSUE TITLE
Uint8List images save in gallery are totally black

### ISSUE THREAD

**Issue by alihassan143** [hui-z/image_gallery_saver#151]
i an saving Uint8List images in gallery and the images of gallery are totally pitch black

**Comment by siyehua** [comment]
I have the same issue

**Comment by siyehua** [comment]
I slove it, I new Flutter version, you should set background in widgets...

**Comment by alihassan143** [comment]
> I slove it, I new Flutter version, you should set background in widgets...

ok i will try
