### ISSUE TITLE
Video files are saving in picture folder !

### ISSUE THREAD

**Issue by shofizone** [hui-z/image_gallery_saver#157]
I am saving file like like this. It should save video file in Movies folder or better if we could give a custom name  as album/folder name!
```
  var data = await ImageGallerySaver.saveFile(
      newFile.path,
      isReturnPathOfIOS: true,
    );
```

**Comment by rogiervandenberg** [comment]
I agree on this. It would be great if you can specify the name of the folder, so you can e.g. name it according to your app, instead of "Pictures".
