### ISSUE TITLE
I/flutter ( 9054): {filePath: null, errorMessage: java.io.FileNotFoundException: /storage/emulated/0/project/1617639888308.jpg: open failed: ENOENT (No such file or directory), isSuccess: false}

### ISSUE THREAD

**Issue by donkii** [hui-z/image_gallery_saver#160]
I have seen all the solutions and tried all of them but none of them worked for me.
I have:

1. Asked for permissions
2. Changed the project name so there is no space in title
3. Added WRITE_EXTERNAL_STORAGE in AndroidManifest.xml
4. Added android:requestLegacyExternalStorage="true"

I am receiving the error on all android version

`
  image_gallery_saver: ^1.6.7`

```
_saveScreen() async {
    PermissionStatus status = await Permission.storage.request();
    if (status.isGranted) {
      RenderRepaintBoundary boundary =
          screenshotGlobalKey.currentContext.findRenderObject();
      ui.Image image = await boundary.toImage();
      ByteData byteData =
          await image.toByteData(format: ui.ImageByteFormat.png);
      final result = await ImageGallerySaver.saveImage(
          byteData.buffer.asUint8List(),
          quality: 100);
      print(result);
      showCustomAlertDialog(context, byteData);
    }
  }
```

Just tested on the ios and everything works fine

**Comment by mikron123** [comment]
Any solution? Happens to me on One+ phone

**Comment by donkii** [comment]
Wasn't able to find anything. For me it's happening on all android devices

**Comment by mikron123** [comment]
Try https://pub.dev/packages/gallery_saver

**Comment by donkii** [comment]
I might need to do that if I can't find a solution for this library.

**Comment by xiaotuguaiguai** [comment]
Any solution? Happens to me

**Comment by ruskakimov** [comment]
Happens only on Android 11 to me.
Compile and target SDK are set to 29.
`android:requestLegacyExternalStorage="true"` is set as well.
