### ISSUE TITLE
Android 11 support and requestLegacyExternalStorage issue.

### ISSUE THREAD

**Issue by lumarama** [hui-z/image_gallery_saver#163]
Google started sending the following message to developers, that means we won't be able to use requestLegacyExternalStorage flag soon and even the alternative permission MANAGE_EXTERNAL_STORAGE will require good reason to get approval. Is that absolutely necessary to request this permission for this plugin, or we can get rid of it?

**Message from Google:** We've detected that your app contains the requestLegacyExternalStorage flag in the manifest file of 1 or more of your app bundles or APKs.

Developers with apps on devices running Android 11+ must use Scoped Storage to give users better access control over their device storage. To release your app on Android 11 or newer after May 5th, you must either:

Update your app to use more privacy friendly best practices, such as the Storage Access Framework or Media Store API
Update your app to declare the All files access (MANAGE_EXTERNAL_STORAGE) permission in the manifest file, and complete the All files access permission declaration in Play Console from May 5th
Remove the All files access permission from your app entirely
For apps targeting Android 11, the requestLegacyExternalStorage flag will be ignored. You must use the All files access permission to retain broad access.

Apps requesting access to the All files access permission without a permitted use will be removed from Google Play, and you won't be able to publish updates.

**Comment by muhammadsaddamnur** [comment]
up

**Comment by CoderJava** [comment]
up

**Comment by fabiohxcx** [comment]
up

**Comment by bakavic** [comment]
I believe this [restriction](https://support.google.com/googleplay/android-developer/answer/10467955) only applies to the case where your `minSdkVersion` is set to >= 30, **AND** the `MANAGE_EXTERNAL_STORAGE` permission is requested.

IIRC, `MANAGE_EXTERNAL_STORAGE` permission started throwing a warning when you uploaded to Play Store since October 2020.

I have tested with `minSdkVersion` set to 30, and no `MANAGE_EXTERNAL_STORAGE` permission, on an Android 10 device (API level 29), a Samsung S9, and I have no issues saving to gallery.

In any case, the `<application android:requestLegacyExternalStorage="true" .....>` flag is ignored for `minSdkVersion` >= 30.

If anyone has issues getting this package to run, do provide some details here, thanks!

**Comment by umaqs** [comment]
As for now, you can target SDK: 29 (android 10) and your app will run fine on android 11 if you have `android:requestLegacyExternalStorage="true"` flag in the manifest file. 

But you won't be able to **update** your app after 5th May unless you use `MANAGE_EXTERNAL_STORAGE` and provide a valid reason as to why you need `all files access` or use other privacy-friendly alternatives.

**Comment by armandojimenez** [comment]
So is there any plan to make this work after May 5th, without adding MANAGE_EXTERNAL_STORAGE After we all upgrade to SDK 30?

**Comment by JAICHANGPARK** [comment]
Any have update this issue? 
I had same problem about this

**Comment by lumarama** [comment]
> As for now, you can target SDK: 29 (android 10) and your app will run fine on android 11 if you have `android:requestLegacyExternalStorage="true"` flag in the manifest file.
> 
> But you won't be able to **update** your app after 5th May unless you use `MANAGE_EXTERNAL_STORAGE` and provide a valid reason as to why you need `all files access` or use other privacy-friendly alternatives.

Also it seems that access to media files isn't a valid reason to get MANAGE_EXTERNAL_STORAGE allowed. See Invalid Uses and Alternatives section: https://support.google.com/googleplay/android-developer/answer/10467955?hl=en#zippy=%2Cpermitted-uses-of-the-all-files-access-permission%2Cinvalid-uses%2Calternatives-to-common-uses

**Comment by armandojimenez** [comment]
So are we safe to use this targeting sdk 30? Im about to deploy my app :(

**Comment by armandojimenez** [comment]
So can I a deploy my new app targeting SDK 30 using this plug in?

**Comment by brightseagit** [comment]
No, you can't deploy the app with SDK>=30 & MANAGE_EXTERNAL_STORAGE. I did try to deploy and my app got rejected by google.

**Comment by 985211yyg** [comment]
https://github.com/985211yyg/ImageGallerySaver.git

**Comment by hajnalbendeguz** [comment]
Any updates on this? 
> Starting in November 2021, app updates will be required to target API level 30 or above

As stated on https://developer.android.com/
