### ISSUE TITLE
ios 真机保存崩溃，模拟器正常

### ISSUE THREAD

**Issue by songkwon** [hui-z/image_gallery_saver#17]

**Comment by xqqlv** [comment]
能贴一下错误日志以及设备信息吗

**Comment by songkwon** [comment]
` PHAssetChangeRequest *assetChangeRequest = [PHAssetChangeRequest creationRequestForAssetFromImage:image];` 执行到这句就会崩溃。
bad access ，什么信息都没有，下面是截图。
![屏幕快照 2019-04-02 下午2 55 19](https://user-images.githubusercontent.com/18206258/55382168-8dbcff00-5557-11e9-97b5-1108611e753e.png)
info.plist里面加了
` Privacy - Photo Library Additions Usage Description `
` Privacy - Photo Library Usage Description ` 
设备是iphoneX, 真机都出现了这个问题

**Comment by xqqlv** [comment]
老哥，你可能用的不是我的库，我没用过这方法。

**Comment by songkwon** [comment]
不好意思，贴错代码了，我是用了这个库，同样的问题，真机就会崩溃

**Comment by xqqlv** [comment]
你能用把android studio运行项目的报错贴一下吗
