### ISSUE TITLE
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.0 and higher.

### ISSUE THREAD

**Issue by Florence2016** [hui-z/image_gallery_saver#18]
FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.0 and higher.
The following dependencies do not satisfy the required version:
project ':image_gallery_saver' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.51

**Comment by xqqlv** [comment]
we will resolve this issue in this week.
