### ISSUE TITLE
iOS image name not correct

### ISSUE THREAD

**Issue by tovidd** [hui-z/image_gallery_saver#183]
```
final Map<dynamic, dynamic> result = await ImageGallerySaver.saveImage(
        myImage,
        name: 'MyImage_${DateTime.now().millisecondsSinceEpoch}',
        isReturnImagePathOfIOS: true,
      );

{isSuccess: true, filePath: file:///Users/username/Library/Developer/CoreSimulator/Devices/ACF82F4C-7CF9-43A6-AA84-38E9DEA5761B/data/Media/DCIM/100APPLE/IMG_0015.JPG}
```

the filename not correct on iOS
device: iOS 14.5 simulator

**Comment by EsteveAguilera** [comment]
I'm having the same issue on an iOS simulator and on an iPhone 6S

**Comment by thenixoncompany** [comment]
I have the same issue but with saveFile it works. The only thing that I don't understand what it means 'isReturnImagePathOfIOS' when is true.

**Comment by warrenm1** [comment]
I was looking into the available code to see if I could fork it with my own changes, and I noticed that in iOS, the `name` argument is discarded by `let _ = arguments["name"],` in the implementations of `savingImageToGallery` and `savingFileToGallery` of the [iOS Plugin](https://github.com/hui-z/image_gallery_saver/blob/master/ios/Classes/SwiftImageGallerySaverPlugin.swift) 

If I understand it correctly, that says that no matter what name we give it, **as the code currently stands**, we have no control over the actual name of the file.

I am not as skilled at writing Swift, so if someone has a temporary solution to this problem, I would be most appreciative. However, if it is not possible, it would at least be nice to have documented somewhere that the `name` parameter is only for Android.
