### ISSUE TITLE
Operation not permitted

### ISSUE THREAD

**Issue by MedvedevAI** [hui-z/image_gallery_saver#184]
stopped working saving on android 11

{filePath: null, errorMessage: java.io.FileNotFoundException: /storage/emulated/0/Pictures/1627397908.jpg: open failed: EPERM (Operation not permitted), isSuccess: false}

**Comment by hanleiZoro** [comment]
I also have this problem

**Comment by chuxia98** [comment]
flutter 2.2 
image_gallery_saver 1.7.0
savefile() have this problem

**Comment by zeeshanayaz** [comment]
Did anyone find the solution?
