### ISSUE TITLE
{filePath: null, errorMessage: java.io.FileNotFoundException: /storage/emulated/0/Pictures/1631614189254.jpg: open failed: EACCES (Permission denied), isSuccess: false}

### ISSUE THREAD

**Issue by Ninad7n** [hui-z/image_gallery_saver#187]

**Comment by fzyzcjy** [comment]
same issue here, how did you solve it?

**Comment by Ninad7n** [comment]
> same issue here, how did you solve it?

Yes, add  
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
Permissions along with
<application
 android:requestLegacyExternalStorage="true"
In android manifest file
Sorry for late reply though.
