### ISSUE TITLE
supports the Android V2 embedding

### ISSUE THREAD

**Issue by mkasaii16** [hui-z/image_gallery_saver#189]
The plugin `image_gallery_saver` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

**Comment by Pavel401** [comment]
Also, i used another package named "image_downloader: ^0.30.0" for downloading files. It's also saying the same thing.

**Comment by hu70258tao** [comment]
> The plugin `image_gallery_saver` uses a deprecated version of the Android embedding.
> To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
> If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

look #186

**Comment by fzyzcjy** [comment]
Same issue here. Hoping it to be solved!

**Comment by Mik77o** [comment]
Same problem...

**Comment by omateuscastro** [comment]
Same issue here.

**Comment by mkasaii16** [comment]
For now, use the " image_save: ^5.0.0 "  to modify the package.

**Comment by davinderkumar** [comment]
use mmoo_image_gallery_saver package from same codebase with required fix.

**Comment by zakblacki** [comment]
image_save and mmoo_image_gallery_saver are good workaround if we wanna use another package 
but it's not a solution

**Comment by lcuis** [comment]
The following lines in `pubspec.yaml` made my project `pub get` without any warning:
```yaml
  image_gallery_saver:
    git:
      url: https://github.com/surfstudio/image_gallery_saver.git
      ref: v2-embedding-migration
```

Thanks to @surfstudio for the plugin adaptations!
