### ISSUE TITLE
filePath: null, errorMessage: java.io.FileNotFoundException: /storage/emulated/0/Pictures/1632214328014.jpg: open failed: EACCES (Permission denied), isSuccess: false

### ISSUE THREAD

**Issue by avnitambaliya31** [hui-z/image_gallery_saver#191]
Future _save() async {
    RenderRepaintBoundary boundary =
        _globalKey.currentContext!.findRenderObject() as RenderRepaintBoundary;
    ui.Image image = await boundary.toImage();
    ByteData byteData =
        (await image.toByteData(format: ui.ImageByteFormat.png))!;
    Uint8List pngBytes = byteData.buffer.asUint8List();
    final result = await ImageGallerySaver.saveImage(
      Uint8List.fromList(pngBytes),
      quality: 80,
    );
    return result;

   }

android.xml file added : 
uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"  < "put this line under"/>
uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" < />
android:requestLegacyExternalStorage="true"

image not save in file storage an get this title error. so, how to fix this problem any one help please!

**Comment by fzyzcjy** [comment]
same here, any thoughts?

**Comment by jacky-yanglei** [comment]
I have the same problem. How can I solve it?

**Comment by TohQiQi** [comment]
I have the same problem also. How can I solve it?

**Comment by avnitambaliya31** [comment]
it was a permission issue,

first add the permission in  permission_handler: ^8.0.1 and get direct the coding page  and add the below code as 

PermissionStatus permission = await Permission.storage.request();
if (permission == PermissionStatus.granted) {
        final result = await ImageGallerySaver.saveImage(
            byteData.buffer.asUint8List(),
            quality: 100);
      } else {
        print("Permission not found");
      }
