### ISSUE TITLE
Execution failed for task ':image_gallery_saver:compileDebugKotlin'.

### ISSUE THREAD

**Issue by JonYun** [hui-z/image_gallery_saver#192]
e: /Users/huangyun/.pub-cache/hosted/pub.flutter-io.cn/image_gallery_saver-1.6.9/android/src/main/kotlin/com/example/imagegallerysaver/ImageGallerySaverPlugin.kt: (19, 7): Redeclaration: ImageGallerySaverPlugin
e: /Users/huangyun/.pub-cache/hosted/pub.flutter-io.cn/image_gallery_saver-1.6.9/android/src/main/kotlin/com/example/imagegallerysaver/ImageGallerySaverPlugin.kt: (113, 7): Redeclaration: SaveResultModel
e: /Users/huangyun/.pub-cache/hosted/pub.flutter-io.cn/image_gallery_saver-1.7.0/android/src/main/kotlin/com/example/imagegallerysaver/ImageGallerySaverPlugin.kt: (21, 7): Redeclaration: ImageGallerySaverPlugin
e: /Users/huangyun/.pub-cache/hosted/pub.flutter-io.cn/image_gallery_saver-1.7.0/android/src/main/kotlin/com/example/imagegallerysaver/ImageGallerySaverPlugin.kt: (29, 52): No value passed for parameter 'registrar'
e: /Users/huangyun/.pub-cache/hosted/pub.flutter-io.cn/image_gallery_saver-1.7.0/android/src/main/kotlin/com/example/imagegallerysaver/ImageGallerySaverPlugin.kt: (30, 22): Unresolved reference: onAttachedToEngine
e: /Users/huangyun/.pub-cache/hosted/pub.flutter-io.cn/image_gallery_saver-1.7.0/android/src/main/kotlin/com/example/imagegallerysaver/ImageGallerySaverPlugin.kt: (118, 7): Redeclaration: SaveResultModel

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':image_gallery_saver:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by JonYun** [comment]
I'm using version 1.7.0

**Comment by jacky-yanglei** [comment]
flutter clean

**Comment by JonYun** [comment]
Already solved , thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月23日(星期四) 下午5:14
收件人: ***@***.***&gt;; 
抄送: "■D&quot; ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hui-z/image_gallery_saver] Execution failed for task &#39;:image_gallery_saver:compileDebugKotlin&#39;. (#192)





 
flutter clean
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by raphaelrca** [comment]
> 

How do you solve it?

**Comment by muhammadramadhan2045** [comment]
> 

how yo u solve it ?

**Comment by eebrerheem** [comment]
Please how do you solve it?

**Comment by PhillipWong0627** [comment]
> Already solved , thank you
> […](#)

bro solved without giving solution, nice

**Comment by shenliwula** [comment]
bro help, giving solution
