### ISSUE TITLE
Raise a bug

### ISSUE THREAD

**Issue by HeroLBJ** [hui-z/image_gallery_saver#193]
in Android  

file  ImageGallerySaverPlugin.kt

method  saveImageToGallery()

`
 val file = generateFile("jpg", name = name)

 bmp.compress(Bitmap.CompressFormat.JPEG, quality, fos)
`
image is jpg ,no png, i need alpha, so 

 val file = generateFile("jpg", name = name)  ==>  val file = generateFile("png", name = name) 
 bmp.compress(Bitmap.CompressFormat.JPEG, quality, fos) ==>  bmp.compress(Bitmap.CompressFormat.PNG, quality, fos)

**Comment by Go-oG** [comment]
We do not currently support png
