### ISSUE TITLE
E/HW-JPEG-DEC(24054): [HME_JPEG_DEC_Delete](3321): HME_JPEG_DEC_Delete: decoder_ctx=null

### ISSUE THREAD

**Issue by Mu7ammadRasul** [hui-z/image_gallery_saver#194]
while i capture my desired widget it gives me an error, despite i handled permissions but seems like it still has something to do with  it, i added read and write permissions but while adding ```android:requestLegacyExternalStorage="true"``` it gave me an error, till i set values below!
compileSdkVersion 30
minSdkVersion 21
targetSdkVersion 30
-----------------------------------------
now i get this on terminal:
E/HW-JPEG-DEC(24054): [HME_JPEG_DEC_Delete](3321): HME_JPEG_DEC_Delete: decoder_ctx=null

**Comment by Mu7ammadRasul** [comment]
so i tested my app on two phones, they are both Huawei but one of them gives me ```E/HW-JPEG-DEC(24054): HME_JPEG_DEC_Delete: HME_JPEG_DEC_Delete: decoder_ctx=null``` error!

**Comment by woodwen** [comment]
Please provide the model number of the Huawei phone in question
