### ISSUE TITLE
Why is it returning to these { filePath: content://media/external/images/media/437} ?

### ISSUE THREAD

**Issue by nooraldin** [hui-z/image_gallery_saver#199]
hello ,
After I updated my project,
I encountered a problem in addition to the difference in returning values
I need the image path with its name as before! (file://.......example.jpg)
Now give me this content://media/external/images/media/437
How can this problem be solved
thanks

my code

`Future<String> saveImage(Uint8List bytes,imageTop) async {
  await [Permission.storage].request();
  final name = 'test';
  // final name = imageName;
  final r1 = await ImageGallerySaver.saveImage(bytes, name: name);
  final r2 = r1["filePath"];
  final imageLink = r2.replaceAll("file://", "");
  return r2;
}`

**Comment by f1dz** [comment]
It happens when you update to version 1.7.1. Downgrade to 1.7.0 will fix this issue
