### ISSUE TITLE
push to dart pub, please

### ISSUE THREAD

**Issue by Seifon** [hui-z/image_gallery_saver#20]
push to dart pub, please!

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.0 and higher.
The following dependencies do not satisfy the required version:
project ':image_gallery_saver' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.51

**Comment by hyjfine** [comment]
1.1.0 pub!
