### ISSUE TITLE
Image saves in a horizontal orientation

### ISSUE THREAD

**Issue by avatarKaran** [hui-z/image_gallery_saver#206]
is this just an error with my phone --- (one plus 7)? all images are saving rotated

**Comment by juanagu** [comment]
Hello @avatarKaran this is a common issue on Android, you can try this: https://stackoverflow.com/questions/60176001/how-to-fix-wrong-rotation-of-photo-from-camera-in-flutter

```
import 'package:image/image.dart' as img;

...

final img.Image capturedImage = img.decodeImage(await File(path).readAsBytes());
final img.Image orientedImage = img.bakeOrientation(capturedImage);
await File(path).writeAsBytes(img.encodeJpg(orientedImage));
```

**Comment by roderikpeeters** [comment]
> Hello @avatarKaran this is a common issue on Android, you can try this: https://stackoverflow.com/questions/60176001/how-to-fix-wrong-rotation-of-photo-from-camera-in-flutter
> 
> ```
> import 'package:image/image.dart' as img;
> 
> ...
> 
> final img.Image capturedImage = img.decodeImage(await File(path).readAsBytes());
> final img.Image orientedImage = img.bakeOrientation(capturedImage);
> await File(path).writeAsBytes(img.encodeJpg(orientedImage));
> ```

How to work this out if you already used ImageGallerySaver.saveImage ?
