### ISSUE TITLE
ImageGallerySaver.saveImage 能不能指定PNG格式啊

### ISSUE THREAD

**Issue by the6nnoo** [hui-z/image_gallery_saver#207]
我看源码指定了JPEG，有时候截图有圆角啥的，生成的图片就是黑了一圈。
要是可以指定生成的格式就好了。

**Comment by YulncBd** [comment]
使用saveFile
String dir = (await getApplicationDocumentsDirectory()).path;
File file = File('${dir}/' + name + '.png');
await file.writeAsBytes(bytes);
final result = await ImageGallerySaver.saveFile(file.path);

**Comment by YulncBd** [comment]
使用saveFile
String dir = (await getApplicationDocumentsDirectory()).path;
File file = File('${dir}/' + name + '.png');
await file.writeAsBytes(bytes);
final result = await ImageGallerySaver.saveFile(file.path);

**Comment by YulncBd** [comment]
使用saveFile
```
String dir = (await getApplicationDocumentsDirectory()).path;
File file = File('${dir}/' + name + '.png');
await file.writeAsBytes(bytes);
final result = await ImageGallerySaver.saveFile(file.path);
```
