### ISSUE TITLE
flutter 2.10 版本不兼容

### ISSUE THREAD

**Issue by 1227228155** [hui-z/image_gallery_saver#208]
E:\flutter2.10.2\flutter\.pub-cache\hosted\pub.flutter-io.cn\image_gallery_saver-1.7.1\android\src\main\kotlin\com\example\imagegallerysaver\ImageGallerySaverPlugin.kt: (73, 28): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.16.

 Flutter 2.10 强制要求 Kotlin 1.5.31 以上的版本

**Comment by zqiuqi007** [comment]
I've got the same question

**Comment by luckysmg** [comment]
+1

**Comment by mariusschroeter** [comment]
any fix?

**Comment by zqiuqi007** [comment]
下载到本地，自己修改下Kotlin 的版本，从本地引入可以解决

**Comment by changkuanlai** [comment]
+1

**Comment by woodwen** [comment]
fix
