### ISSUE TITLE
Returning wrong file path

### ISSUE THREAD

**Issue by OrchiDorchi** [hui-z/image_gallery_saver#211]
Hi,
I recently installed this package. When I use saveImage method, it returns `{filePath: content://media/external/images/media/36, errorMessage: null, isSuccess: true}`. After saving, I need to upload the photo to another app, but it throws this exception.
`FileSystemException: Cannot open file, path = 'content://media/external/images/media/36' (OS Error: No such file or directory, errno = 2)`. How can I access the true path?
Thanks.

PS: I am already on version 1.7.0

**Comment by f1dz** [comment]
Please make sure you are adding this ```image_gallery_saver: 1.7.0``` not ```image_gallery_saver: ^1.7.0```
Put ```^``` in front of the version will update the package to the available minor version (latest 1.7.x).

To check the installed version on your project, you can open ```pubspec.lock``` and search ```image_gallery_saver```

**Comment by OrchiDorchi** [comment]
Thanks for your help. It works when I write ^1.7.0

**Comment by KBRR11** [comment]
@OrchiDorchi How can I get the path to put it in a File('path'), because when I put this path content://media/external/video/media/221826 I get an error in this case it is an mp4 video
