### ISSUE TITLE
请问你们导出来模糊吗？我这边导出图片很模糊。What should I do if the generated picture is blurry?

### ISSUE THREAD

**Issue by easonccc** [hui-z/image_gallery_saver#216]

**Comment by HyBLF** [comment]
+1，被压缩了，请问解决了吗？

**Comment by trieucq** [comment]
<img width="650" alt="Screenshot 2023-10-20 at 11 04 44" src="https://github.com/hui-z/image_gallery_saver/assets/134939249/4dafab11-ede3-4b8a-8b99-5ef3c16118ac">

Here is my code.
ui.Image image = await boundary.toImage(pixelRatio: 5.0);
Please raise the pixelRatio, it will solve the problem
