### ISSUE TITLE
app crush when i save photo

### ISSUE THREAD

**Issue by ECat4** [hui-z/image_gallery_saver#22]
app crush issue. when i save use save

**Comment by ECat4** [comment]
ios simulator

**Comment by xqqlv** [comment]
can you post error messahe？

**Comment by Florence2016** [comment]
same here with me thisi is the error message
 === BUILD TARGET image_gallery_saver OF PROJECT Pods WITH CONFIGURATION Debug ===
.pub-cache/hosted/pub.dartlang.org/image_gallery_saver-1.1.0/ios/Classes/ImageGallerySaverPlugin.m:2:9: fatal error: 'image_gallery_saver/image_gallery_saver-Swift.h' file not found
    #import <image_gallery_saver/image_gallery_saver-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
