### ISSUE TITLE
image_gallery_saver_v3也是你开发的吗？

### ISSUE THREAD

**Issue by Dboy233** [hui-z/image_gallery_saver#227]
如果是的话。
有个问题。

在执行pod install的时候。找不到podspec文件。
原因是文件名是 image_gallery_saver.podspec  插件名是image_gallery_saver_v3

修改为image_gallery_saver_v3.podspec 和文件内的名字之后就可以了。这个是否需要需要修复一下。

**Comment by peakerWu** [comment]
我都改了，还是不行，报这个错误
```
 image_gallery_saver_v3 (from `../lib_flutter/.ios/.symlinks/plugins/image_gallery_saver_v3/ios`) was resolved to 1.5.0, which depends on
      Flutter

Specs satisfying the `Flutter (from `../lib_flutter/.ios/Flutter`), Flutter` dependency were found, but they required a higher minimum deployment target.
```

**Comment by Dboy233** [comment]
> 我都改了，还是不行，报这个错误
> 
> ```
>  image_gallery_saver_v3 (from `../lib_flutter/.ios/.symlinks/plugins/image_gallery_saver_v3/ios`) was resolved to 1.5.0, which depends on
>       Flutter
> 
> Specs satisfying the `Flutter (from `../lib_flutter/.ios/Flutter`), Flutter` dependency were found, but they required a higher minimum deployment target.
> ```

其实不用V3也可以。。。我已经不用_v3了

**Comment by zakblacki** [comment]
Does not work with ios pod install symlink not found V3

**Comment by faisalmushtaq007** [comment]
Any solutions??
