### ISSUE TITLE
FileNotFoundException: /storage/emulated/0/M-Path/1555858813855.png (No such file or directory)

### ISSUE THREAD

**Issue by sc00n** [hui-z/image_gallery_saver#23]
When I execute the following code:
`    ByteData bytes = await rootBundle.load('assets/logotemp3.png');`
 `   final result = await ImageGallerySaver.save(bytes.buffer.asUint8List());`

I get the following Exception, and nothing is saved to my gallery:

`W/System.err(24588): java.io.FileNotFoundException: /storage/emulated/0/M-Path/1555858813855.png (No such file or directory)
W/System.err(24588): 	at java.io.FileOutputStream.open0(Native Method)
W/System.err(24588): 	at java.io.FileOutputStream.open(FileOutputStream.java:287)
W/System.err(24588): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:223)
W/System.err(24588): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
W/System.err(24588): 	at com.example.imagegallerysaver.ImageGallerySaverPlugin.saveImageToGallery(ImageGallerySaverPlugin.kt:48)
W/System.err(24588): 	at com.example.imagegallerysaver.ImageGallerySaverPlugin.onMethodCall(ImageGallerySaverPlugin.kt:32)
W/System.err(24588): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
W/System.err(24588): 	at io.flutter.view.FlutterNativeView$PlatformMessageHandlerImpl.handleMessageFromDart(FlutterNativeView.java:188)
W/System.err(24588): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:202)
W/System.err(24588): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(24588): 	at android.os.MessageQueue.next(MessageQueue.java:325)
W/System.err(24588): 	at android.os.Looper.loop(Looper.java:142)
W/System.err(24588): 	at android.app.ActivityThread.main(ActivityThread.java:6673)
W/System.err(24588): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(24588): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
W/System.err(24588): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)
`

 Flutter doctor -v
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17763.437], locale nl-BE)
    • Flutter version 1.2.1 at C:\src\flutter\flutter
    • Framework revision 8661d8aecd (9 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\u0084978\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] Connected device (1 available)
    • moto g 6 plus • ZY32335VSQ • android-arm64 • Android 8.0.0 (API 26)

• No issues found!

**Comment by xqqlv** [comment]
you need to ask for storage permission to save the image. I using https://github.com/BaseflowIT/flutter-permission-handler to handle permission for me.

**Comment by sc00n** [comment]
Thanks, it worked! I used https://pub.dartlang.org/packages/permission_handler. Maybe you should add some information on this in your example or introduction?

**Comment by CosmicPangolin** [comment]
Agreed, ran into the same issue.  :)

**Comment by naeem-hasan** [comment]
Ran into the same issue, now fixed. You can close your issue now.

**Comment by donkii** [comment]
I am giving permission but still having the same problem

>   _saveScreen() async {
    PermissionStatus status = await Permission.storage.request();
    if (status.isGranted) {
      RenderRepaintBoundary boundary =
      _screenshotGlobalKey.currentContext.findRenderObject();
      ui.Image image = await boundary.toImage();
      ByteData byteData = await image.toByteData(
          format: ui.ImageByteFormat.png);
      final result =
      await ImageGallerySaver.saveImage(
          byteData.buffer.asUint8List(), quality: 100);
    }
  }

**Comment by xiejibiao** [comment]
@donkii I have encountered the same problem, and I have requested the permission to save, but there is still an exception. This exception only appears on Android. IOS can be saved successfully. Have you solved it?
