### ISSUE TITLE
OS Error: No such file or directory, errno = 2

### ISSUE THREAD

**Issue by alfietapping** [hui-z/image_gallery_saver#237]
I'm trying to save an image to users device and get the file path back to store in a db so i can use the image in the app. This works fine on IOS, but on Android it gives me back this file path:

`filePath: content://media/external/images/media/1000006846`

And when trying to use this path in an image widget, i get this error:

`'content://media/external/images/media/100000686' (OS Error: No such file or direct`

**Comment by TechHelper** [comment]
@alfietapping Did you find any solution. I also need exact file path like this /../test.jpg because I want to upload that image.

**Comment by Go-oG** [comment]
The path is in Content-Uri format. You should use the Android contentResolver to load the data, see 'https://developer.android.com/training/data-storage/shared/media’
