### ISSUE TITLE
=== BUILD TARGET image_gallery_saver OF PROJECT Pods WITH CONFIGURATION Debug ===

### ISSUE THREAD

**Issue by Florence2016** [hui-z/image_gallery_saver#24]
.pub-cache/hosted/pub.dartlang.org/image_gallery_saver-1.1.0/ios/Classes/ImageGallerySaverPlugin.m:2:9: fatal error: 'image_gallery_saver/image_gallery_saver-Swift.h' file not found
    #import <image_gallery_saver/image_gallery_saver-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

**Comment by Florence2016** [comment]
i hope for immediate response thank.. 👍

**Comment by yang-chao** [comment]
> .pub-cache/hosted/pub.dartlang.org/image_gallery_saver-1.1.0/ios/Classes/ImageGallerySaverPlugin.m:2:9: fatal error: 'image_gallery_saver/image_gallery_saver-Swift.h' file not found
> #import <image_gallery_saver/image_gallery_saver-Swift.h>
> ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 1 error generated.

H, there, have you solved this problem?

**Comment by yang-chao** [comment]
Problem solved!
1. Edit .m file, replace #import <image_gallery_saver/image_gallery_saver-Swift.h> with #import <image_gallery_saver-Swift.h>
2. Refer to this post https://stackoverflow.com/questions/52536380/why-linker-link-static-libraries-with-errors-ios, add an empty swift file and create bridging header.

**Comment by ZHanOBa** [comment]
Thanks for sharing。

**Comment by ZHanOBa** [comment]
Thanks for sharing

**Comment by ZHanOBa** [comment]
我页遇到了同样的问题，解决方法如下：
1.卸载掉插件，重新安装

2.创建新的桥接文件

3.编辑.m文件，将#import <image_gallery_saver-Swift.h>替换为#import <image_gallery_saver/image_gallery_saver-Swift.h>，和楼上说的相反

4.运行！

5.保存到相册功能可以正常使用！
