### ISSUE TITLE
project ':image_gallery_saver' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.72，what can i do?

### ISSUE THREAD

**Issue by guduqiucai** [hui-z/image_gallery_saver#243]
FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':image_gallery_saver' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.72

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by wukonget** [comment]
您解决了么，我也遇到这个问题

**Comment by black-purple** [comment]
Facing the same issue as well.

**Comment by DaemonChoejur** [comment]
Any updates on this?

**Comment by black-purple** [comment]
> Any updates on this?

Apart form @wukonget's response, no there isn't any update, for the time being I'm using that solution and it works for me, so no complaints.

**Comment by SheepYang1993** [comment]
> 可以直接通过git引用
> 
> image_gallery_saver: git: url: [git@github.com](mailto:git@github.com):hui-z/image_gallery_saver.git ref: master

it works

**Comment by PhillipWong0627** [comment]
> > 可以直接通过git引用
> > image_gallery_saver: git: url: [git@github.com](mailto:git@github.com):hui-z/image_gallery_saver.git ref: master
> 
> it works

where to apply this?
