### ISSUE TITLE
content://media/external/images/media/1000006846' (OS Error: No such file or directory, errno = 2)

### ISSUE THREAD

**Issue by alfietapping** [hui-z/image_gallery_saver#244]
when saving an image on Android and getting the file path back to display an image it gives me this error

'content://media/external/images/media/1000006846' (OS Error: No such file or directory, errno = 2)`

This is the file path it gives me back

`filePath: content://media/external/images/media/1000006846`

Code im using:

```
  Future<String> saveImage(Uint8List image) async {
    var response =
        await ImageGallerySaver.saveImage(image, isReturnImagePathOfIOS: true);
    if (Platform.isAndroid) {
      return response['filePath'].toString();
    } else {
      return response['filePath'].toString().replaceAll(RegExp('file://'), '');
    }
  }
```

**Comment by woodwen** [comment]
1. Confirm whether the media file exists under the specified URI path.

2. Check that your app has the correct permission to read external storage. The following permissions can be added to the AndroidManifest.xml file:

``` kotlin
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
```

Then request that permission at runtime.

Also, please provide the Android version and phone model

**Comment by juria** [comment]
As I am experiencing exactly the same issue, I can provide my device details. I'm using the emulated Pixel 6 with Android 13 (API 33).

**Comment by Go-oG** [comment]
It is recommended to load the data via ContentResolver

**Comment by bfhddjjdjxjdk** [comment]
hejjd

**Comment by bfhddjjdjxjdk** [comment]
hdh

**Comment by gabielchong** [comment]
any update?

**Comment by 18211308** [comment]
...

**Comment by KhanNguyen099** [comment]
Future<String> saveImage(Uint8List image) async {
    var response =
        await ImageGallerySaver.saveImage(image, isReturnImagePathOfIOS: true);
    if (Platform.isAndroid) {
      return response['filePath'].toString();
    } else {
      return response['filePath'].toString().replaceAll(RegExp('file://'), '');
    }
  }

**Comment by Cruzillian** [comment]
Just learning all the technically complex jargon as I go along, so I can speak better "NERD".
If someone were to put a gun to my head and told me to explain how... I'd be all like, "I can't! But I can SHOW you how!"

**Comment by qaisamin** [comment]
> when saving an image on Android and getting the file path back to display an image it gives me this error
> 
> 'content://media/external/images/media/1000006846' (OS Error: No such file or directory, errno = 2)`
> 
> This is the file path it gives me back
> 
> `filePath: content://media/external/images/media/1000006846`
> 
> Code im using:
> 
> ```
>   Future<String> saveImage(Uint8List image) async {
>     var response =
>         await ImageGallerySaver.saveImage(image, isReturnImagePathOfIOS: true);
>     if (Platform.isAndroid) {
>       return response['filePath'].toString();
>     } else {
>       return response['filePath'].toString().replaceAll(RegExp('file://'), '');
>     }
>   }
> ```
> 
>

**Comment by ahammamlho** [comment]
I face the same issue

**Comment by Wataru1090** [comment]
> As I am experiencing exactly the same issue, I can provide my device details. I'm using the emulated Pixel 6 with Android 13 (API 33).

**Comment by Wataru1090** [comment]
> > Jk

**Comment by sainajannat** [comment]
![ei_1736613753060-removebg-preview](https://github.com/user-attachments/assets/d83faa90-6cc9-41e5-a21b-92c484634e04)

**Comment by sainajannat** [comment]
Top Cleansing Service

**Comment by sainajannat** [comment]
Top Cleansing Service

**Comment by BAYU1994-2025** [comment]
Play and jaclpotplay

**Comment by lourdesvaca** [comment]
Update?

**Comment by sgbvjncx** [comment]
Future<String> saveImage(Uint8List image) async {
    var response =
        await ImageGallerySaver.saveImage(image, isReturnImagePathOfIOS: true);
    if (Platform.isAndroid) {
      return response['filePath'].toString();
    } else {
      return response['filePath'].toString().replaceAll(RegExp('file://'), '');
    }
  }

**Comment by Nguyendinhtuan17** [comment]
> when saving an image on Android and getting the file path back to display an image it gives me this error
> 
> 'content://media/external/images/media/1000006846' (OS Error: No such file or directory, errno = 2)`
> 
> This is the file path it gives me back
> 
> `filePath: content://media/external/images/media/1000006846`
> 
> Code im using:
> 
> ```
>   Future<String> saveImage(Uint8List image) async {
>     var response =
>         await ImageGallerySaver.saveImage(image, isReturnImagePathOfIOS: true);
>     if (Platform.isAndroid) {
>       return response['filePath'].toString();
>     } else {
>       return response['filePath'].toString().replaceAll(RegExp('file://'), '');
>     }
>   }
> ```

**Comment by Fuckthefakes** [comment]
[content://media/external/downloads/1000000316](GitHub_enterprize)yml.md

**Comment by yousufmirpro** [comment]
Keep your eyes on the stars, and your feet on the ground.

**Comment by yousufmirpro** [comment]
Keep your eyes on the stars, and your feet on the ground.

**Comment by rica15899** [comment]
Future<String> saveImage(Uint8List image) async {
    var response =
        await ImageGallerySaver.saveImage(image, isReturnImagePathOfIOS: true);
    if (Platform.isAndroid) {
      return response['filePath'].toString();
    } else {
      return response['filePath'].toString().replaceAll(RegExp('file://'), '');
    }
  }

**Comment by Manhatthien-98** [comment]
> khi lưu hình ảnh trên Android và lấy lại đường dẫn tệp để hiển thị hình ảnh, nó báo lỗi này
> 
> 'content://media/external/images/media/1000006846' (Lỗi hệ điều hành: Không có tệp hoặc thư mục nào như vậy, errno = 2)`
> 
> Đây là đường dẫn tập tin nó trả về cho tôi
> 
> `filePath: content://media/external/images/media/1000006846`
> 
> Mã tôi đang sử dụng:
> 
> ```
>   Future<String> saveImage(Uint8List image) async {
>     var response =
>         await ImageGallerySaver.saveImage(image, isReturnImagePathOfIOS: true);
>     if (Platform.isAndroid) {
>       return response['filePath'].toString();
>     } else {
>       return response['filePath'].toString().replaceAll(RegExp('file://'), '');
>     }
>   }
> ```

https://github.com/hui-z/image_gallery_saver/issues/244#issue-1612834285


> khi lưu hình ảnh trên Android và lấy lại đường dẫn tệp để hiển thị hình ảnh, nó báo lỗi này
> 
> 'content://media/external/images/media/1000006846' (Lỗi hệ điều hành: Không có tệp hoặc thư mục nào như vậy, errno = 2)`
> 
> Đây là đường dẫn tập tin nó trả về cho tôi
> 
> `filePath: content://media/external/images/media/1000006846`
> 
> Mã tôi đang sử dụng:
> 
> ```
>   Future<String> saveImage(Uint8List image) async {
>     var response =
>         await ImageGallerySaver.saveImage(image, isReturnImagePathOfIOS: true);
>     if (Platform.isAndroid) {
>       return response['filePath'].toString();
>     } else {
>       return response['filePath'].toString().replaceAll(RegExp('file://'), '');
>     }
>   }
> ```

https://github.com/hui-z/image_gallery_saver/issues/244
https://github.com/hui-z/image_gallery_saver/issues/244#issue-1612834285

**Comment by its2badwespend** [comment]
```


```

**Comment by Manhatthien-98** [comment]
> khi lưu hình ảnh trên Android và lấy lại đường dẫn tệp để hiển thị hình ảnh, nó báo lỗi này
> 
> 'content://media/external/images/media/1000006846' (Lỗi hệ điều hành: Không có tệp hoặc thư mục nào như vậy, errno = 2)`
> 
> Đây là đường dẫn tập tin nó trả về cho tôi
> 
> `filePath: content://media/external/images/media/1000006846`
> 
> Mã tôi đang sử dụng:
> 
> ```
>   Future<String> saveImage(Uint8List image) async {
>     var response =
>         await ImageGallerySaver.saveImage(image, isReturnImagePathOfIOS: true);
>     if (Platform.isAndroid) {
>       return response['filePath'].toString();
>     } else {
>       return response['filePath'].toString().replaceAll(RegExp('file://'), '');
>     }
>   }
> ```

https://github.com/hui-z/image_gallery_saver/issues/244#issue-1612834285
https://github.com/hui-z/image_gallery_saver/issues/244

**Comment by sgbvjncx** [comment]
Future<String> saveImage(Uint8List image) async {
    var response =
        await ImageGallerySaver.saveImage(image, isReturnImagePathOfIOS: true);
    if (Platform.isAndroid) {
      return response['filePath'].toString();
    } else {
      return response['filePath'].toString().replaceAll(RegExp('file://'), '');
    }
  }

**Comment by sgbvjncx** [comment]
Future<String> saveImage(Uint8List image) async {
    var response =
        await ImageGallerySaver.saveImage(image, isReturnImagePathOfIOS: true);
    if (Platform.isAndroid) 

- > {

      return response['filePath'].toString();
    } else {
      return response['filePath'].toString().replaceAll(RegExp('file://'), '');
    }
  }

**Comment by RoyBoy1025** [comment]
[supported_devices (1).csv](https://github.com/user-attachments/files/19902341/supported_devices.1.csv)

**Comment by RoyBoy1025** [comment]
[supported_devices (1).csv](https://github.com/user-attachments/files/19902344/supported_devices.1.csv)p

**Comment by HAMODE726** [comment]
content://media/external/downloads/1000001993

**Comment by faisarnawfar** [comment]
Teamtechlink. Net. Lk

![Image](https://github.com/user-attachments/assets/30f79020-5ef7-4bc8-8293-0114a5ebcb43)

**Comment by Cleanskiier27** [comment]
content://media/external/file/1000000055 /android/content/rate/create/deflate.android/inflate.content/create.android/content

[RTF Reader-1.0.0-backup-export-all.JSON.txt](https://github.com/user-attachments/files/21209555/RTF.Reader-1.0.0-backup-export-all.JSON.txt)

**Comment by lyyfong287-lang** [comment]
https://www.facebook.com/share/1Qjkbja9qt/

**Comment by mesokp978-maker** [comment]
content://media/external/downloads/1000005838

**Comment by solseavfong-commits** [comment]
https://github.com/hui-z/image_gallery_saver/issues/244

**Comment by solseavfong-commits** [comment]
https://github.com/hui-z/image_gallery_saver/issues/244
https://www.facebook.com/share/1EZPvZywJe/

**Comment by ss9398045-source** [comment]
Dk win

**Comment by ss9398045-source** [comment]
hack

**Comment by Modibo07** [comment]
Comment héberger mon site ?

**Comment by hrbk327-boop** [comment]
[vlog website .html](https://github.com/user-attachments/files/24489049/vlog.website.html)

**Comment by hrbk327-boop** [comment]
This website is make for the online website 
Please

**Comment by alfyfbshar17-wq** [comment]
- [ ] https://github.com/hui-z/image_gallery_saver/issues/244

**Comment by alfyfbshar17-wq** [comment]
_https://github.com/hui-z/image_gallery_saver/issues/244_

**Comment by cunharodolfo524-cpu** [comment]
https://github.com/hui-z/image_gallery_saver/issues/244 open

**Comment by cunharodolfo524-cpu** [comment]
https://github.com/hui-z/image_gallery_saver/issues/244 aberto

**Comment by Cleanskiier27** [comment]
https://maps.google.com/?q=302+Fir+Dr%2C+Durango%2C+CO+81301&ftid=0x873eaa76cbff6e9d:0x5a93240d83504118&hl=en&gl=us&entry=ac

**Comment by parvinbhai19826-lang** [comment]
<img width="1536" height="1024" alt="Image" src="https://github.com/user-attachments/assets/5924579c-34ce-4b87-85cf-ca848744b11e" />

**Comment by parvinbhai19826-lang** [comment]
**BDTHBGF🥹ZRYFFYCICZDVVDJJD👙**

**Comment by valdenir26656-stack** [comment]
content://media/external/file/1000029752

**Comment by valdenir26656-stack** [comment]
content://media/external/file/1000029752

**Comment by valdenir26656-stack** [comment]
[](url)content://media/external/file/1000029752

**Comment by nomangunjial80** [comment]
Website me chang karo

**Comment by kogasthkasra-max** [comment]
> It is recommended to load the data via ContentResolver

****

**Comment by edsongabrielzz40-creator** [comment]
> when saving an image on Android and getting the file path back to display an image it gives me this error
> 
> 'content://media/external/images/media/1000006846' (OS Error: No such file or directory, errno = 2)`
> 
> This is the file path it gives me back
> 
> `filePath: content://media/external/images/media/1000006846`
> 
> Code im using:
> 
> ```
>   Future<String> saveImage(Uint8List image) async {
>     var response =
>         await ImageGallerySaver.saveImage(image, isReturnImagePathOfIOS: true);
>     if (Platform.isAndroid) {
>       return response['filePath'].toString();
>     } else {
>       return response['filePath'].toString().replaceAll(RegExp('file://'), '');
>     }
>   }
> ```

**Comment by abwsfyanaljyly1-jpg** [comment]
Future<String> saveImage(Uint8List image) async {
    var response =
        await ImageGallerySaver.saveImage(image, isReturnImagePathOfIOS: true);
    if (Platform.isAndroid) {
      return response['filePath'].toString();
    } else {
      return response['filePath'].toString().replaceAll(RegExp('file://'), '');
    }
  }
