### ISSUE TITLE
GIF files only the first frame is getting saved in iOS

### ISSUE THREAD

**Issue by kamtasingh27** [hui-z/image_gallery_saver#248]
Only the first frame is getting saved when trying to save a GIF file in iOS.

Refer - https://github.com/localsend/localsend/issues/430, https://github.com/hui-z/image_gallery_saver/issues/77

**Comment by woodwen** [comment]
_saveNetworkGifFile() async {
    var appDocDir = await getTemporaryDirectory();
    String savePath = appDocDir.path + "/temp.gif";
    String fileUrl =
        "https://hyjdoc.oss-cn-beijing.aliyuncs.com/hyj-doc-flutter-demo-run.gif";
    await Dio().download(fileUrl, savePath);
    final result =
        await ImageGallerySaver.saveFile(savePath, isReturnPathOfIOS: true);
    print(result);
  }
