### ISSUE TITLE
on iOS Simulator when saving image this is the error

### ISSUE THREAD

**Issue by Florence2016** [hui-z/image_gallery_saver#26]
=== BUILD TARGET image_gallery_saver OF PROJECT Pods WITH CONFIGURATION Debug ===

**.pub-cache/hosted/pub.dartlang.org/image_gallery_saver-1.1.0/ios/Classes/ImageGallerySaverPlugin.m:2:9: fatal error: 'image_gallery_saver/image_gallery_saver-Swift.h' file not found
    #import <image_gallery_saver/image_gallery_saver-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.**

**Comment by Florence2016** [comment]
I hope for immediate response @hyjfine

**Comment by xqqlv** [comment]
you must use swift project
