### ISSUE TITLE
Image is not saving into gallery in apk, but it works in emulator

### ISSUE THREAD

**Issue by Sanya-L** [hui-z/image_gallery_saver#262]
Image manage to be save into gallery in emulator, but it not working in apk. 
Both using andriod 10/11, permission_handler: ^10.4.3, image_gallery_saver: ^2.0.3

**Comment by aliwaseem72** [comment]
Did you add permission in manifest file
**android:requestLegacyExternalStorage="true"**

**Comment by Go-oG** [comment]
Please check whether the relevant read/write permissions are compatible
