### ISSUE TITLE
报错参数错误{filePath: null, errorMessage: parameters error, isSuccess: false}

### ISSUE THREAD

**Issue by silveryTitan** [hui-z/image_gallery_saver#265]
以下是用法：
print(image.getBytes());
                    var saveImage = await ImageGallerySaver.saveImage(
                        image.getBytes(),
                        name: 'ic_invite_${index + 1}');
                    print(saveImage);
看过源码 只有当质量为空或者imageBytes为空才会报错 但是质量是默认的 我打印了image.getBytes() 是有值返回的 
image来源是Image库的合成图片代码 ：
var bgData = await rootBundle
                      .load('${Constant.ASSETS_IMG}ic_invite_${index + 1}.png');
                  var codeData = await rootBundle
                      .load('${Constant.ASSETS_IMG}icon_white.png');
                  var bg = img.decodeImage(bgData.buffer.asUint8List());
                  var code = img.decodeImage(codeData.buffer.asUint8List());
                  if (bg != null && code != null) {
                    var image =
                        img.compositeImage(bg, code, dstX: 105, dstY: 413);
使用的版本是   image_gallery_saver: 2.0.3
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 128, 191, 4, 255, 180, 193, 58, 255, 178, 192, 106, 253, 178, 191, 143, 254, 177, 191, 183, 255,...
请问应该怎么解决？

**Comment by DragonK1ng** [comment]
我也是遇到这个问题

**Comment by DragonK1ng** [comment]
在main文件下的AndroidManifest.xml里加上试试：<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

**Comment by DragonK1ng** [comment]
在main文件下的AndroidManifest.xml里加上试试：
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

**Comment by DragonK1ng** [comment]
去main文件上的AndroidManifest.xml补上这个权限：uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"，自己加上xml的标签</>，大概这样子 < uses-permission.........STORAGE" />

**Comment by Go-oG** [comment]
Please check whether the relevant read/write permissions are compatible
