### ISSUE TITLE
Save image error : No such file or directory

### ISSUE THREAD

**Issue by maxcong** [hui-z/image_gallery_saver#28]
`W/System.err( 6526): java.io.FileNotFoundException: /storage/emulated/0/jiupai/1558158842041.png (No such file or directory)
W/System.err( 6526): 	at java.io.FileOutputStream.open0(Native Method)
W/System.err( 6526): 	at java.io.FileOutputStream.open(FileOutputStream.java:308)
W/System.err( 6526): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:238)
W/System.err( 6526): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:180)
W/System.err( 6526): 	at com.example.imagegallerysaver.ImageGallerySaverPlugin.saveImageToGallery(ImageGallerySaverPlugin.kt:48)
W/System.err( 6526): 	at com.example.imagegallerysaver.ImageGallerySaverPlugin.onMethodCall(ImageGallerySaverPlugin.kt:32)
W/System.err( 6526): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
W/System.err( 6526): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:90)
W/System.err( 6526): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:234)
W/System.err( 6526): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err( 6526): 	at android.os.MessageQueue.next(MessageQueue.java:326)
W/System.err( 6526): 	at android.os.Looper.loop(Looper.java:160)
W/System.err( 6526): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
W/System.err( 6526): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 6526): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
W/System.err( 6526): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

**Comment by xainpro** [comment]
any solution yet ?

**Comment by HannibalKcc** [comment]
[issue 13](https://github.com/hui-z/image_gallery_saver/issues/13) ?

**Comment by xqqlv** [comment]
using https://github.com/BaseflowIT/flutter-permission-handler to handle permission
