### ISSUE TITLE
is best to return a path

### ISSUE THREAD

**Issue by jenics** [hui-z/image_gallery_saver#34]
Thanks to provider so cool plugin that we can save image to system gallery easyly.
hope to have a new feature as the code shown below.

final filePath= await ImageGallerySaver.save(byteData.buffer.asUint8List());
var savedFile = File.fromUri(Uri.file(filePath));

By the way, with the savedFile uri, we can share it .

**Comment by kleinpetr** [comment]
It will be very usefull, is it possible to make update soon? Thanks

**Comment by xqqlv** [comment]
Now doing
