### ISSUE TITLE
Doesn't seem to run at all, with error about swift version

### ISSUE THREAD

**Issue by chornbe** [hui-z/image_gallery_saver#36]
Using Flutter 1.7.8, MacOS and XCode fully up to date, getting the following error trying to use the library. Should this be something I need to set?

...
    - `image_gallery_saver` does not specify a Swift version and none of the targets (`Runner`) integrating it
    have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at
    least one of the targets that integrate this pod.

    /usr/local/Cellar/cocoapods/1.7.1/libexec/gems/cocoapods-1.7.1/lib/cocoapods/installer/xcode/target_validator
    .rb:122:in `verify_swift_pods_swift_version'
    /usr/local/Cellar/cocoapods/1.7.1/libexec/gems/cocoapods-1.7.1/lib/cocoapods/installer/xcode/target_validator
    .rb:37:in `validate!'
    /usr/local/Cellar/cocoapods/1.7.1/libexec/gems/cocoapods-1.7.1/lib/cocoapods/installer.rb:578:in
    `validate_targets'
    /usr/local/Cellar/cocoapods/1.7.1/libexec/gems/cocoapods-1.7.1/lib/cocoapods/installer.rb:158:in `install!'
    /usr/local/Cellar/cocoapods/1.7.1/libexec/gems/cocoapods-1.7.1/lib/cocoapods/command/install.rb:51:in `run'
    /usr/local/Cellar/cocoapods/1.7.1/libexec/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /usr/local/Cellar/cocoapods/1.7.1/libexec/gems/cocoapods-1.7.1/lib/cocoapods/command.rb:52:in `run'
    /usr/local/Cellar/cocoapods/1.7.1/libexec/gems/cocoapods-1.7.1/bin/pod:55:in `<top (required)>'
    /usr/local/Cellar/cocoapods/1.7.1/libexec/bin/pod:22:in `load'
    /usr/local/Cellar/cocoapods/1.7.1/libexec/bin/pod:22:in `<main>'

**Comment by kroppli** [comment]
the same

**Comment by tieorange** [comment]
+1

**Comment by tieorange** [comment]
Addding this to podfile doesn't help me:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['SWIFT_VERSION'] = '4.2'
    end
  end
end
```

**Comment by lorentz-wu** [comment]
+1 same

**Comment by zfy1988** [comment]
+1 same

**Comment by chornbe** [comment]
I removed the library, built my app, and released it without this library. 

At this point I'd much rather just pay for a commercial library that works and has support. This one won't be finding its way into my project, sadly. 

Thanks anyway
