### ISSUE TITLE
'image_gallery_saver/image_gallery_saver-Swift.h' file not found

### ISSUE THREAD

**Issue by lorentz-wu** [hui-z/image_gallery_saver#39]
image_gallery_saver/image_gallery_saver-Swift.h' file not found
    #import <image_gallery_saver/image_gallery_saver-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    Pods-Runner-dwokpppkepdbjiegihihefqywwom
    note: Using new build systemnote: Planning buildnote: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone Xʀ.

**Comment by zfy1988** [comment]
+same

**Comment by xqqlv** [comment]
you need create project with swift
只能用于swift的项目

**Comment by wuujiann** [comment]
Ran into this issue today when I tried to build iOS app using flutter.  Can you provide detail steps, with screen shots if possible, of creating project with swift to resolve this issue?  Sorry, I'm new to iOS development.

```
flutter build ios --no-codesign 
Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
Building xyz.joewu.btguest for device (ios-release)...
Running pod install...                                              1.0s
Running Xcode build...                                                  
Xcode build done.                                            1.7s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    shared_preferences-ecdftdlsessmeqbydyobcruftruf
    /opt/flutter/.pub-cache/hosted/pub.dartlang.org/image_gallery_saver-1.2.2/ios/Classes/ImageGallerySaverPlugin.m:2:9: fatal error:
    'image_gallery_saver/image_gallery_saver-Swift.h' file not found
    #import <image_gallery_saver/image_gallery_saver-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    /opt/flutter/.pub-cache/hosted/pub.dartlang.org/image_gallery_saver-1.2.2/ios/Classes/ImageGallerySaverPlugin.m:2:9: fatal error:
    'image_gallery_saver/image_gallery_saver-Swift.h' file not found
    #import <image_gallery_saver/image_gallery_saver-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by wuujiann** [comment]
Found solution here: https://github.com/hui-z/image_gallery_saver/issues/24

1. Edit .m file (in my case: _/opt/flutter/.pub-cache/hosted/pub.dartlang.org/image_gallery_saver-1.2.2/ios/Classes/ImageGallerySaverPlugin.m_), replace 
`    #import <image_gallery_saver/image_gallery_saver-Swift.h> `
with 
`    #import <image_gallery_saver-Swift.h>`
2. Refer to this post https://stackoverflow.com/questions/52536380/why-linker-link-static-libraries-with-errors-ios, add an empty swift file and create bridging header.
3. Run it!

**Comment by conghaonet** [comment]
> Found solution here: #24
> 
> 1. Edit .m file (in my case: _/opt/flutter/.pub-cache/hosted/pub.dartlang.org/image_gallery_saver-1.2.2/ios/Classes/ImageGallerySaverPlugin.m_), replace
>    `   #import <image_gallery_saver/image_gallery_saver-Swift.h>`
>    with
>    `    #import <image_gallery_saver-Swift.h>`
> 2. Refer to this post https://stackoverflow.com/questions/52536380/why-linker-link-static-libraries-with-errors-ios, add an empty swift file and create bridging header.
> 3. Run it!

It is working to me
