### ISSUE TITLE
Saving from file path

### ISSUE THREAD

**Issue by aloisdeniel** [hui-z/image_gallery_saver#40]
Reading a file from local storage as a `Uint8List`, sending it to platform, then deserializing content from other side can take time (at least on Android).

Maybe giving an other method to save a file from its  path could reduce that extra-processing time ?

### Edit

[I forked and implemented the Android method](https://github.com/aloisdeniel/image_gallery_saver/commit/b60da5f819df37693a1b278dc11ce53512268f77) and it is a lot more performant now!

**Comment by xqqlv** [comment]
v1.2.0 is supported
