### ISSUE TITLE
v1.2.0, saveImage, does not return the saved file path, but only a bool result

### ISSUE THREAD

**Issue by yintaibing** [hui-z/image_gallery_saver#46]

**Comment by xqqlv** [comment]
because it's gallery path，I fell it's useless，but if necessary，i can add path next version

**Comment by hahafather007** [comment]
我也觉得返回值是文件的路径非常有必要，这个布尔值拿来根本没啥用...

**Comment by hahafather007** [comment]
@xqqlv

**Comment by hahafather007** [comment]
或者直接返回文件，如果保存失败就返回null都比一个布尔值有用

**Comment by yintaibing** [comment]
@xqqlv 
yes! file path is necessary, plz add it~~~

**Comment by ianpark** [comment]
File path is required to show the file in the app, and also for deleting the image. Or is there any other way doing it without the file path?

**Comment by xqqlv** [comment]
v1.2.1
