### ISSUE TITLE
Android build apk failed

### ISSUE THREAD

**Issue by dingputongxi** [hui-z/image_gallery_saver#48]
> Configure project :app
WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getMergeAssets(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getProcessResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display a
stack trace.

> Configure project :image_gallery_saver
         *********************************************************
WARNING: This version of connectivity will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************

**Comment by 123lxw123** [comment]
试试最新版本，现在迁移到 AndroidX 了

**Comment by dingputongxi** [comment]
> 试试最新版本，现在迁移到 AndroidX 了
> (try to update to latest version. Migrate to AndroidX now)

谢谢
