### ISSUE TITLE
安卓保存视频打印为true但是没看到视频在哪

### ISSUE THREAD

**Issue by ZiTengHuang** [hui-z/image_gallery_saver#50]
我试了好几台安卓手机、找不到视频在哪里。

**Comment by ZiTengHuang** [comment]
private fun generateFile(): File {
    val storePath =  Environment.getExternalStorageDirectory().absolutePath + File.separator + getApplicationName()
    val appDir = File(storePath)
    if (!appDir.exists()) {
      appDir.mkdir()
    }
    val fileName = System.currentTimeMillis().toString() + ".png"
    return File(appDir, fileName)
  }


统一写成png了  老哥  ！。

**Comment by xqqlv** [comment]
v1.2.1
