### ISSUE TITLE
使用 rawRgba 报错

### ISSUE THREAD

**Issue by jjjachyty** [hui-z/image_gallery_saver#54]
java.lang.IllegalStateException: BitmapFactory.decodeByteArray(image,0,image.size) must not be null

**Comment by hyjfine** [comment]
please test in latest version

**Comment by Jcdroid** [comment]
version: 1.6.0
android: 8.0.0
Exception: java.lang.IllegalStateException: BitmapFactory.decodeByteArray(image,0,image.size) must not be null
