### ISSUE TITLE
Plugin crashing in JobScheduler because activity is null

### ISSUE THREAD

**Issue by westracer** [hui-z/image_gallery_saver#61]
_registrar.activity()_ needs to be checked that it is not null, otherwise it crashes while being executed inside JobScheduler.

> 2019-10-30 17:50:54.159 16607-16607/? D/TSBackgroundFetch: 💀 [HeadlessTask]
> 2019-10-30 17:50:54.742 16607-16607/? E/JobServiceEngine: Error while executing job: 998
> 2019-10-30 17:50:54.742 16607-16607/? D/AndroidRuntime: Shutting down VM
> 2019-10-30 17:50:54.743 16607-16607/? E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: com.example, PID: 16607
>     java.lang.RuntimeException: java.lang.IllegalStateException: registrar.activity() must not be null
>         at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:112)
>         at android.os.Handler.dispatchMessage(Handler.java:106)
>         at android.os.Looper.loop(Looper.java:214)
>         at android.app.ActivityThread.main(ActivityThread.java:7076)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
>      Caused by: java.lang.IllegalStateException: registrar.activity() must not be null
>         at carnegietechnologies.gallery_saver.GallerySaverPlugin$Companion.registerWith(GallerySaverPlugin.kt:17)
>         at carnegietechnologies.gallery_saver.GallerySaverPlugin.registerWith(Unknown Source:2)
>         at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:28)
>         at com.example.Application.registerWith(Application.java:18)
>         at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.initFlutterView(HeadlessTask.java:133)
>         at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.<init>(HeadlessTask.java:47)
>         at com.transistorsoft.flutter.backgroundfetch.HeadlessJobService.onStartJob(HeadlessJobService.java:38)
>         at android.app.job.JobService$1.onStartJob(JobService.java:62)
>         at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:108)
>         at android.os.Handler.dispatchMessage(Handler.java:106) 
>         at android.os.Looper.loop(Looper.java:214) 
>         at android.app.ActivityThread.main(ActivityThread.java:7076)

**Comment by mserena** [comment]
same problem :)

**Comment by zplblue** [comment]
anybody can fix or explain this?
