### ISSUE TITLE
can i save base64 string to image  ?

### ISSUE THREAD

**Issue by jagdishjadeja** [hui-z/image_gallery_saver#62]
I have base64 string of image from database
can I save that?

**Comment by cgdzin** [comment]
String imageBase64="image from database...";

var result = await ImageGallerySaver.saveImage(dataFromBase64String(imageBase64));
print(result);

 ...

import 'dart:typed_data';
  static Uint8List dataFromBase64String(String base64String) {
    return base64Decode(base64String);
  }

**Comment by jagdishjadeja** [comment]
Thank you its done
