### ISSUE TITLE
java.io.FileNotFoundException: /storage/emulated/0/APP_NAME/1573113036325.png: open failed: ENOENT (No such file or directory)

### ISSUE THREAD

**Issue by ChenPengHuang** [hui-z/image_gallery_saver#63]
W/System.err( 5899): 	at libcore.io.IoBridge.open(IoBridge.java:496)
W/System.err( 5899): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
W/System.err( 5899): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
W/System.err( 5899): 	at com.example.imagegallerysaver.ImageGallerySaverPlugin.saveImageToGallery(ImageGallerySaverPlugin.kt:61)
W/System.err( 5899): 	at com.example.imagegallerysaver.ImageGallerySaverPlugin.onMethodCall(ImageGallerySaverPlugin.kt:33)
W/System.err( 5899): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
W/System.err( 5899): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
W/System.err( 5899): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
W/System.err( 5899): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err( 5899): 	at android.os.MessageQueue.next(MessageQueue.java:336)
W/System.err( 5899): 	at android.os.Looper.loop(Looper.java:180)
W/System.err( 5899): 	at android.app.ActivityThread.main(ActivityThread.java:7520)
W/System.err( 5899): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 5899): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
W/System.err( 5899): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
W/System.err( 5899): Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
W/System.err( 5899): 	at libcore.io.Linux.open(Native Method)
W/System.err( 5899): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
W/System.err( 5899): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
W/System.err( 5899): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
W/System.err( 5899): 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7419)
W/System.err( 5899): 	at libcore.io.IoBridge.open(IoBridge.java:482)
W/System.err( 5899): 	... 14 more`

**Comment by cgdzin** [comment]
W/System.err(16563): java.io.FileNotFoundException: /storage/emulated/0/app/1573196433255.png (No such file or directory)
W/System.err(16563):     at java.io.FileOutputStream.open0(Native Method)
W/System.err(16563):     at java.io.FileOutputStream.open(FileOutputStream.java:308)
W/System.err(16563):     at java.io.FileOutputStream.<init>(FileOutputStream.java:238)
W/System.err(16563):     at java.io.FileOutputStream.<init>(FileOutputStream.java:180)
W/System.err(16563):     at com.example.imagegallerysaver.ImageGallerySaverPlugin.saveImageToGallery(ImageGallerySaverPlugin.kt:61)
W/System.err(16563):     at com.example.imagegallerysaver.ImageGallerySaverPlugin.onMethodCall(ImageGallerySaverPlugin.kt:33)
W/System.err(16563):     at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
W/System.err(16563):     at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
W/System.err(16563):     at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
W/System.err(16563):     at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(16563):     at android.os.MessageQueue.next(MessageQueue.java:326)
W/System.err(16563):     at android.os.Looper.loop(Looper.java:183)
W/System.err(16563):     at android.app.ActivityThread.main(ActivityThread.java:7266)
W/System.err(16563):     at java.lang.reflect.Method.invoke(Native Method)
W/System.err(16563):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
W/System.err(16563):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)

**Comment by ChenPengHuang** [comment]
Android  10

**Comment by ihihihihihihih** [comment]
https://pub.dev/packages/permission_handler

import permission_handler

```
// first   
                   if (Platform.isAndroid) {
                        PermissionStatus permissionStorage =
                            await PermissionHandler().checkPermissionStatus(PermissionGroup.storage);
                        if (permissionStorage != PermissionStatus.granted) {
                          Map<PermissionGroup, PermissionStatus> permissionStatus =
                              await PermissionHandler().requestPermissions([PermissionGroup.storage]);
                          permissionStorage = permissionStatus[PermissionGroup.storage] ?? PermissionStatus.unknown;

                          if (permissionStorage != PermissionStatus.granted) {
                            print("❌----------has no Permission");
                            return;
                          }
                        }
                      }
//  second
    var response = await Dio().get("https://ss0.baidu.com/94o3dSag_xI4khGko9WTAnF6hhy/image/h%3D300/sign=a62e824376d98d1069d40a31113eb807/838ba61ea8d3fd1fc9c7b6853a4e251f94ca5f46.jpg", options: Options(responseType: ResponseType.bytes));
    final result = await ImageGallerySaver.saveImage(Uint8List.fromList(response.data));
    print(result);
```

**Comment by kateile** [comment]
I have storage permission granted. but still this problem occurs. I have noticed it happen in android 10

**Comment by hyjfine** [comment]
please upgrade latest version and check.

**Comment by LevinGermann** [comment]
The issue still exists in version 1.5.0 of image_gallery_saver.

**Comment by hyjfine** [comment]
> The issue still exists in version 1.5.0 of image_gallery_saver.
> 
> > W/System.err(16568): java.io.FileNotFoundException: /storage/emulated/0/Cluecity/1593430565744.jpg: open failed: EACCES (Permission denied)
> > W/System.err(16568): 	at libcore.io.IoBridge.open(IoBridge.java:496)
> > W/System.err(16568): 	at java.io.FileOutputStream.(FileOutputStream.java:235)
> > W/System.err(16568): 	at java.io.FileOutputStream.(FileOutputStream.java:186)
> > W/System.err(16568): 	at com.example.imagegallerysaver.ImageGallerySaverPlugin.saveImageToGallery(ImageGallerySaverPlugin.kt:64)
> > W/System.err(16568): 	at com.example.imagegallerysaver.ImageGallerySaverPlugin.onMethodCall(ImageGallerySaverPlugin.kt:36)
> > W/System.err(16568): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
> > W/System.err(16568): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
> > W/System.err(16568): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
> > W/System.err(16568): 	at android.os.MessageQueue.nativePollOnce(Native Method)
> > W/System.err(16568): 	at android.os.MessageQueue.next(MessageQueue.java:336)
> > W/System.err(16568): 	at android.os.Looper.loop(Looper.java:174)
> > W/System.err(16568): 	at android.app.ActivityThread.main(ActivityThread.java:7697)
> > W/System.err(16568): 	at java.lang.reflect.Method.invoke(Native Method)
> > W/System.err(16568): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
> > W/System.err(16568): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
> > W/System.err(16568): Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
> > W/System.err(16568): 	at libcore.io.Linux.open(Native Method)
> > W/System.err(16568): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
> > W/System.err(16568): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
> > W/System.err(16568): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
> > W/System.err(16568): 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7596)
> > W/System.err(16568): 	at libcore.io.IoBridge.open(IoBridge.java:482)
> > W/System.err(16568): 	... 14 more
> 
> Happening with this code:
> 
> ```
> if (await Permission.storage.request().isGranted) {  
>   // Either the permission was already granted before or the user just granted it.  
>   await ImageGallerySaver.saveImage(Uint8List.fromList(response.data));  
> }
> ```
> 
> It used to work before I upgraded to Android 10. I think even Permission.photos was enough, didn't even need to request storage permissions...

yes,  the plugin not compatible with scoped storage,  as the android doc [https://developer.android.com/training/data-storage/use-cases#opt-out-scoped-storage](url):
- Target Android 9 (API level 28) or lower.
- If you target Android 10 (API level 29) or higher, set the value of requestLegacyExternalStorage to true in your app's manifest file
<manifest ... >

  <application android:requestLegacyExternalStorage="true" ... >
    ...
  </application>
</manifest>

**Comment by cookmscott** [comment]
I'm on version `1.5.0` and I tried both targeting Android API 28 (without legacy external storage) and API 29 with external storage true, both returned `No such file or directory`

**Comment by davizgarzia** [comment]
I'm having the same issue...

**Comment by IllyaSikeryn** [comment]
The same issue is here!

**Comment by hussamDana92** [comment]
I'm having the same issue

**Comment by ganeshchenniah** [comment]
is it fixed ? I m also getting same errro .

**Comment by IllyaSikeryn** [comment]
I ended up using this solution that works - If you target Android 10 (API level 29) or higher, set the value of requestLegacyExternalStorage to true in your app's manifest file

**Comment by nezoat** [comment]
same issue.    
"requestLegacyExternalStorage" didn't fix it.

**Comment by cookmscott** [comment]
Android 10 (API 29) was released more than a year ago. If this issue isn't addressed, it should be stated in the README that it does not work consistently with latest versions of Android.

**Comment by rao21** [comment]
Is this issue resolved?

**Comment by DenizDogan92** [comment]
I got the same issue and solved this using "permission_handler" package. 
You can import "permission_handler" and request for a storage permission before you saved the file.

For example:
```
    PermissionStatus status = await Permission.storage.request();
    final result = await ImageGallerySaver.saveImage(
        Uint8List.fromList(Img.encodeJpg(image)),
        quality: 90,
        name: 'test');
```

**Comment by miamihotline** [comment]
Add this <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" /> before application tag
to your AndroidManifest.xml

**Comment by Abhilash-sringar-12** [comment]
If targetSdkVersion is 30 android:requestLegacyExternalStorage="true" doesn't work!
Please change targetSdkVersion  to 29 and add android:requestLegacyExternalStorage="true" in Manifest file. It works fine!

**Comment by shukaka** [comment]
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

add permissions above worked for me.

**Comment by shukaka** [comment]
`<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />`
add permissions above worked for me.

**Comment by mohamedmohamedtaha** [comment]
This problem is strange I didn't fix , I tried all solution but no benefit.

**Comment by Burhanyaprak** [comment]
I'm having this problem too, any solution?

**Comment by asiisultan1981** [comment]
having same issue: didn't solve by putting "requestLegacyExternalStorage to true" in manifest nor by reducing sdk to 29.

**Comment by nehad-alyafi** [comment]
having the same error

**Comment by LinoQuirogaMusic** [comment]
i have the same error, and all it's looking fine

**Comment by AsadullahArif** [comment]
what should we use for android 13
