### ISSUE TITLE
How display Video from local storage to Gallary

### ISSUE THREAD

**Issue by AkramChauhan** [hui-z/image_gallery_saver#67]
This plugin works like charm for Network images/videos.
I managed to display local images in the gallery which was created by my flutter app.
I am not sure, how to display video in a gallery from local storage.

Here is my code for saving an image from the temp folder and display in the gallery.

```
                Uri myUri = Uri.parse(widget.imgPath);
                File originalImageFile = new File.fromUri(myUri);
                Uint8List bytes;
                await originalImageFile.readAsBytes().then((value) {
                  bytes = Uint8List.fromList(value);
                  print('reading of bytes is completed');
                }).catchError((onError) {
                  print('Exception Error while reading audio from path:' +
                      onError.toString());
                });
                final result = await ImageGallerySaver.saveImage(Uint8List.fromList(bytes));
                print(result);
```

Here is what I am doing for saving temp video to a specific directory.

```
              File originalVideoFile = File(widget.videoFile);
              Directory directory = await getExternalStorageDirectory();
              if(!Directory("${directory.path}/Downloaded Status/Videos").existsSync()){
                Directory("${directory.path}/Downloaded Status/Videos").createSync(recursive: true);
              }
              String path = directory.path;
              String curDate = DateTime.now().toString();
              String newFileName = "$path/Downloaded Status/Videos/VIDEO-$curDate.mp4";
              print(newFileName);
              await originalVideoFile.copy(newFileName);
```

but this video is not visible in Gallary.
I need some help to display this video in the gallery.
-Thanks.

**Comment by lisen87** [comment]
you can try image_pickers 1.0.5+3

**Comment by lisen87** [comment]
@AkramChauhan you can try image_pickers 1.0.5+3

**Comment by Udaychinthala** [comment]
@AkramChauhan  
use this line of code after saving the file to your local path
await ImageGallerySaver.saveFile(local_path);
in your case 
await ImageGallerySaver.saveFile("$path/Downloaded Status/Videos/VIDEO-$curDate.mp4");

**Comment by hyjfine** [comment]
> This plugin works like charm for Network images/videos.
> I managed to display local images in the gallery which was created by my flutter app.
> I am not sure, how to display video in a gallery from local storage.
> 
> Here is my code for saving an image from the temp folder and display in the gallery.
> 
> ```
>                 Uri myUri = Uri.parse(widget.imgPath);
>                 File originalImageFile = new File.fromUri(myUri);
>                 Uint8List bytes;
>                 await originalImageFile.readAsBytes().then((value) {
>                   bytes = Uint8List.fromList(value);
>                   print('reading of bytes is completed');
>                 }).catchError((onError) {
>                   print('Exception Error while reading audio from path:' +
>                       onError.toString());
>                 });
>                 final result = await ImageGallerySaver.saveImage(Uint8List.fromList(bytes));
>                 print(result);
> ```
> 
> Here is what I am doing for saving temp video to a specific directory.
> 
> ```
>               File originalVideoFile = File(widget.videoFile);
>               Directory directory = await getExternalStorageDirectory();
>               if(!Directory("${directory.path}/Downloaded Status/Videos").existsSync()){
>                 Directory("${directory.path}/Downloaded Status/Videos").createSync(recursive: true);
>               }
>               String path = directory.path;
>               String curDate = DateTime.now().toString();
>               String newFileName = "$path/Downloaded Status/Videos/VIDEO-$curDate.mp4";
>               print(newFileName);
>               await originalVideoFile.copy(newFileName);
> ```
> 
> but this video is not visible in Gallary.
> I need some help to display this video in the gallery.
> -Thanks.

any more details? phone and OS info?

**Comment by lisen87** [comment]
image_pickers @hyjfine

**Comment by hyjfine** [comment]
ok
