### ISSUE TITLE
Setting file name

### ISSUE THREAD

**Issue by zoogi** [hui-z/image_gallery_saver#68]
How can I set a name for images?  current saving names are like "1573725322960.png". I want to enter the file name.

**Comment by hyjfine** [comment]
implement in latest version

**Comment by FRANIAZA** [comment]
Hello ImageGallerySaver.saveFile(path), doesn't keep the filename provided in the path and sets it to something like 1573725322960.png

**Comment by danieljiwonkang98** [comment]
Can we have update for this cannot saveimage with change names like mentioned. @hyjfine
