### ISSUE TITLE
Image orientation change sometimes

### ISSUE THREAD

**Issue by LaCharcaSoftware** [hui-z/image_gallery_saver#70]
Hi! Sometimes the images change the initial orientation. Is there a way to save or check the metadata of the images?
For example, in my flutter app I see a vertical orientation of an image, however when I save the image the orientation change to horizontal.

**Comment by hyjfine** [comment]
I can not reproduce this issue

**Comment by Mehu007** [comment]
I am facing the same issue.
The downloaded image is sometimes rotated.
