### ISSUE TITLE
image_gallery_saver-Swift.h file not found

### ISSUE THREAD

**Issue by 77251380** [hui-z/image_gallery_saver#71]
I try to build the project with image_gallery_saver 1.2.2,then xcode report this error 'image_gallery_saver/image_gallery_saver-Swift.h file not found'

**Comment by Xadovsk** [comment]
Same problem here. Works great on Android but no on IOS

**Comment by 77251380** [comment]
Finally i modify the file "ImageGallerySaverPlugin.m" which the error line show. then it works.
the head file must modify to #import "image_gallery_saver-Swift.h"

**Comment by tolstenko** [comment]
Here is the pr https://github.com/hui-z/image_gallery_saver/pull/73
You can use this pubspec.yaml in the mean time
```
image_gallery_saver:
    git: git://github.com/sthormio/image_gallery_saver
```

**Comment by sur950** [comment]
Replace the following line

`#import <image_gallery_saver-Swift.h>`

with

`#import <image_gallery_saver/image_gallery_saver-Swift.h>`

It will work for sure.

**Comment by hyjfine** [comment]
fixed
