### ISSUE TITLE
kotlin.io.NoSuchFileException

### ISSUE THREAD

**Issue by chethanprabhakar** [hui-z/image_gallery_saver#72]
Hi,

I'm using image_gallery_saver to save videos in my app. I get this error

```
kotlin.io.NoSuchFileException: /data/user/0/com.example.app/cache/record/f1759ee46913f0d844c6280f555d3125-1575211960680.mp4: The source file doesn't exist.
```

What am i missing?

Thanks,
Chethan

**Comment by kldMohammed** [comment]
you should check if the file exist or not 

`if (file.exists()) {
	//do something
}`

**Comment by hyjfine** [comment]
> you should check if the file exist or not
> 
> `if (file.exists()) { //do something }`
> 
> am not using this library but i faced this problem today and when i google for it i found your question and solve it by this way, and hope it will help you
