### ISSUE TITLE
IOS保存网络图片失败，也不报错

### ISSUE THREAD

**Issue by liuyun1014** [hui-z/image_gallery_saver#74]

**Comment by liuyun1014** [comment]
真机版本9.3.2 权限也都加了
        <key>NSAppleMusicUsageDescription</key>
	<string>App需要您的同意,才能访问媒体资料库</string>
	<key>NSCalendarsUsageDescription</key>
	<string>App需要您的同意,才能访问日历</string>
	<key>NSCameraUsageDescription</key>
	<string>允许使用相机权限</string>
	<key>NSContactsUsageDescription</key>
	<string>App需要您的同意，才能访问通讯录</string>
	<key>NSLocationAlwaysUsageDescription</key>
	<string>App需要您的同意,才能始终访问位置</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>App需要您的同意,才能在使用期间访问位置</string>
	<key>NSMicrophoneUsageDescription</key>
	<string>允许使用麦克风权限</string>
	<key>NSMotionUsageDescription</key>
	<string>App需要您的同意,才能访问运动与健身</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>请求访问相册</string>
	<key>NSSpeechRecognitionUsageDescription</key>
	<string>语音识别权限</string>
	<key>UIBackgroundModes</key>
	<array>
		<string>fetch</string>
		<string>remote-notification</string>
	</array>
	<key>ITSAppUsesNonExemptEncryption</key>
	<false/>
	<key>NSPhotoLibraryAddUsageDescription</key>
	<string></string>

**Comment by lcxmagic** [comment]
1、权限的问题，
2、saveImage方法在IOS下返回值为bool类型。
我也遇到了这样的问题，但是是第二种

**Comment by hyjfine** [comment]
return false when failed
