### ISSUE TITLE
flutter 1.12.15 编译apk时报错 Permission denied

### ISSUE THREAD

**Issue by hustlemickey** [hui-z/image_gallery_saver#75]
在 flutter 1.10.14 版本中 ，编译没问题。
在 flutter 1.12.15 版本中
编译apk报错，具体日志

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

command
flutter build apk --target-platform android-arm,android-arm64 --split-per-abi

exception
ProcessException: ProcessException: Permission denied
Command: /Users/mickeystone/flutter/.pub-cache/hosted/pub.dartlang.org/image_gallery_saver-1.2.2/android/gradlew -I=/Users/mickeystone/flutter/packages/flutter_tools/gradle/aar_init_script.gradle -Pflutter-root=/Users/mickeystone/flutter -Poutput-dir=/Users/mickeystone/wor/flutter_wtf/build/app -Pis-plugin=true -Ptarget-platform=android-arm,android-arm64,android-x64 assembleAarRelease

#0      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:266:37)
<asynchronous suspension>
#1      buildGradleAar (package:flutter_tools/src/android/gradle.dart:548:33)
#2      buildPluginsAsAar (package:flutter_tools/src/android/gradle.dart:711:13)
<asynchronous suspension>
#3      buildGradleApp (package:flutter_tools/src/android/gradle.dart:257:11)
#4      buildGradleApp (package:flutter_tools/src/android/gradle.dart:415:19)
<asynchronous suspension>
#5      _AndroidBuilderImpl.buildApk (package:flutter_tools/src/android/android_builder.dart:97:13)
#6      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:106:26)
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#10     _rootRun (dart:async/zone.dart:1126:13)
#11     _CustomZone.run (dart:async/zone.dart:1023:19)
#12     _runZoned (dart:async/zone.dart:1518:10)
#13     runZoned (dart:async/zone.dart:1465:12)
#14     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#15     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#16     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#17     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#19     _rootRun (dart:async/zone.dart:1126:13)
#20     _CustomZone.run (dart:async/zone.dart:1023:19)
#21     _runZoned (dart:async/zone.dart:1518:10)
#22     runZoned (dart:async/zone.dart:1465:12)
#23     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#24     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#25     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#26     new Future.sync (dart:async/future.dart:224:31)
#27     CommandRunner.run (package:args/command_runner.dart:112:14)
#28     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#29     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#30     _rootRun (dart:async/zone.dart:1126:13)
#31     _CustomZone.run (dart:async/zone.dart:1023:19)
#32     _runZoned (dart:async/zone.dart:1518:10)
#33     runZoned (dart:async/zone.dart:1502:12)
#34     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#35     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#36     _rootRun (dart:async/zone.dart:1126:13)
#37     _CustomZone.run (dart:async/zone.dart:1023:19)
#38     _runZoned (dart:async/zone.dart:1518:10)
#39     runZoned (dart:async/zone.dart:1465:12)
#40     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#41     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#42     run (package:flutter_tools/runner.dart:50:10)
#43     main (package:flutter_tools/executable.dart:65:9)
#44     main (file:///Users/mickeystone/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#45     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#46     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
flutter doctor
�[32m[✓]�[39m Flutter (Channel unknown, v1.12.14, on Mac OS X 10.15.1 19B88, locale zh-Hans-PH)
    �[32m•�[39m Flutter version 1.12.14 at /Users/mickeystone/flutter
    �[32m•�[39m Framework revision 7726910a5b (6 天前), 2019-11-25 16:47:51 -0500
    �[32m•�[39m Engine revision c89ac6347b
    �[32m•�[39m Dart version 2.7.0

�[32m[✓]�[39m Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    �[32m•�[39m Android SDK at /Users/mickeystone/Library/Android/sdk
    �[32m•�[39m Android NDK location not configured (optional; useful for native profiling support)
    �[32m•�[39m Platform android-29, build-tools 29.0.2
    �[32m•�[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    �[32m•�[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    �[32m•�[39m All Android licenses accepted.

�[32m[✓]�[39m Xcode - develop for iOS and macOS (Xcode 11.2.1)
    �[32m•�[39m Xcode at /Applications/Xcode.app/Contents/Developer
    �[32m•�[39m Xcode 11.2.1, Build version 11B53
    �[32m•�[39m CocoaPods version 1.8.4

�[32m[✓]�[39m Android Studio (version 3.5)
    �[32m•�[39m Android Studio at /Applications/Android Studio.app/Contents
    �[32m•�[39m Flutter plugin version 41.1.2
    �[32m•�[39m Dart plugin version 191.8593
    �[32m•�[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

�[32m[✓]�[39m IntelliJ IDEA Ultimate Edition (version 2019.3)
    �[32m•�[39m IntelliJ at /Users/mickeystone/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    �[32m•�[39m Flutter plugin version 41.1.5
    �[32m•�[39m Dart plugin version 193.5432

�[33m[!]�[39m VS Code (version 1.40.1)
    �[32m•�[39m VS Code at /Applications/Visual Studio Code.app/Contents
    �[31m✗�[39m Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

�[32m[✓]�[39m Connected device (1 available)
    �[32m•�[39m iPhone 8 • DD1B2F21-6F6A-474A-908A-3FA5D3EAE79D • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)

�[33m!�[39m Doctor found issues in 1 category.

**Comment by BB-fat** [comment]
我是在更新了最新的flutter稳定版之后遇到了这个问题，ios正常，但是安卓构建的时候报错：
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'androidx.core:core' has different version for the compile (1.0.0-rc01) and runtime (1.1.0) classpath. You should manually set the same version via DependencyResolution

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin image_gallery_saver...
Running Gradle task 'assembleAarRelease'...
Finished with error: ProcessException: Permission denied
  Command: /Users/bbfat/flutter/.pub-cache/hosted/pub.flutter-io.cn/image_gallery_saver-1.2.2/android/gradlew -I=/Users/bbfat/flutter/packages/flutter_tools/gradle/aar_init_script.gradle -Pflutter-root=/Users/bbfat/flutter -Poutput-dir=/Users/bbfat/Desktop/esw_app/build/app -Pis-plugin=true -Ptarget-platform=android-arm,android-arm64,android-x64 assembleAarRelease

```

**Comment by hustlemickey** [comment]
手动修改 gradlew权限解决，
修改  /Users/当前用户/flutter/.pub-cache/hosted/pub.flutter-io.cn/image_gallery_saver-1.2.2/android/gradlew    权限为 755 解决
