### ISSUE TITLE
do not support saving gif

### ISSUE THREAD

**Issue by yugona** [hui-z/image_gallery_saver#77]
When saved gif to gallery , gif will not move any more.

**Comment by mahesh-iphonedev** [comment]
Use below code with gif image url instead of video url. It works

_saveVideo() async {
    var appDocDir = await getTemporaryDirectory();
    String savePath = appDocDir.path + "/temp.mp4";
    await Dio().download("http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4", savePath);
    final result = await ImageGallerySaver.saveFile(savePath);
    print(result);
 }

**Comment by huntrist** [comment]
> Use below code with gif image url instead of video url. And change "/temp.mp4" to "/temp.gif" It works
> 
> _saveVideo() async {
> var appDocDir = await getTemporaryDirectory();
> String savePath = appDocDir.path + "/temp.mp4";
> await Dio().download("http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4", savePath);
> final result = await ImageGallerySaver.saveFile(savePath);
> print(result);
> }

this does NOT seem to work on iOS with image_gallery_saver 1.2.2, flutter v1.12.13+hotfix.8

**Comment by hyjfine** [comment]
please try upgrade and use 
`_saveGif() async {
    var appDocDir = await getTemporaryDirectory();
    String savePath = appDocDir.path + "/temp.gif";
    String fileUrl =
        "https://hyjdoc.oss-cn-beijing.aliyuncs.com/hyj-doc-flutter-demo-run.gif";
    await Dio().download(fileUrl, savePath);
    final result = await ImageGallerySaver.saveFile(savePath);
    print(result);
    _toastInfo("$result");
  }`

**Comment by sunjianan9900** [comment]
> please try upgrade and use like example
> `_saveGif() async { var appDocDir = await getTemporaryDirectory(); String savePath = appDocDir.path + "/temp.gif"; String fileUrl = "https://hyjdoc.oss-cn-beijing.aliyuncs.com/hyj-doc-flutter-demo-run.gif"; await Dio().download(fileUrl, savePath); final result = await ImageGallerySaver.saveFile(savePath); print(result); _toastInfo("$result"); }`

好像还是不行，先把gif保存到临时目录，再用ImageGallerySaver.saveFile(savePath)保存到相册，相册里的就是不动。
然后我打开模拟器的目录，发现临时目录下的temp.gif是可以动的

**Comment by RicoRogers** [comment]
我遇到同样的问题，保存后就不动了，请问有解决办法吗

**Comment by haoyuant** [comment]
我遇到同样的问题，保存后gif不会动了，请问怎么解决

**Comment by kimyLee** [comment]
Does this problem has some solution ? Or some other method to save gif to gallery is help for me, 3s a lot
