### ISSUE TITLE
'image_gallery_saver/image_gallery_saver-Swift.h' file not found

### ISSUE THREAD

**Issue by jinliyuelong** [hui-z/image_gallery_saver#80]
when i use 1.2.2,but error which is  'image_gallery_saver/image_gallery_saver-Swift.h' file not found happened.

**Comment by a451492549** [comment]
me too!

**Comment by YDJSZY** [comment]
I have the same problem now

**Comment by Luozf12345** [comment]
+1

**Comment by mixiaodou** [comment]
What causes it? How to solve

**Comment by mixiaodou** [comment]
Solved the problem：
- In ImageGallerySaverPlugin.m file ,
Replace #import "image_gallery_saver-Swift.h"   with  
#import <image_gallery_saver/image_gallery_saver-Swift.h>

It's strange I don't know why
