### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by PillarChen** [hui-z/image_gallery_saver#82]
* What went wrong:
A problem occurred configuring project ':image_gallery_saver'.
> Could not resolve all artifacts for configuration ':image_gallery_saver:classpath'.
   > Could not download httpclient.jar (org.apache.httpcomponents:httpclient:4.5.3)
      > Could not get resource 'https://jcenter.bintray.com/org/apache/httpcomponents/httpclient/4.5.3/httpclient-4.5.3.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/apache/httpcomponents/httpclient/4.5.3/httpclient-4.5.3.jar'.
            > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   > Could not download httpcore.jar (org.apache.httpcomponents:httpcore:4.4.6)
      > Could not get resource 'https://jcenter.bintray.com/org/apache/httpcomponents/httpcore/4.4.6/httpcore-4.4.6.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/apache/httpcomponents/httpcore/4.4.6/httpcore-4.4.6.jar'.
            > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by hyjfine** [comment]
please check you network.
