### ISSUE TITLE
Plugin not saving images on Android 10

### ISSUE THREAD

**Issue by Zazo032** [hui-z/image_gallery_saver#83]
The method [`getExternalStorageDirectory()`](https://github.com/hui-z/image_gallery_saver/blob/master/android/src/main/kotlin/com/example/imagegallerysaver/ImageGallerySaverPlugin.kt#L45) is deprecated on Android 10+, so it doesn't save the image. Would it be possible to add a workaround to make it work on Android 10+ devices?

Related to https://github.com/flutter/flutter/issues/48208

**Comment by Zazo032** [comment]
As a workaround, you can add `android:requestLegacyExternalStorage="true"` to your `AndroidManifest.xml`'s `application` tag (it will work until Android 11)

**Comment by scsfwgy** [comment]
+1,android10 no work
![image](https://user-images.githubusercontent.com/16045179/74125171-75a21b80-4c0f-11ea-9669-85afee1412bc.png)

**Comment by shpy2001** [comment]
> As a workaround, you can add `android:requestLegacyExternalStorage="true"` to your `AndroidManifest.xml`'s `application` tag (it will work until Android 11)

After do that and edit compileSdkVersion=29 , i can build but still have another fail :

![image](https://user-images.githubusercontent.com/18063702/74509625-91b9fb80-4f34-11ea-8d12-757d8b9e0991.png)

**Comment by amondnet** [comment]
https://developer.android.com/training/data-storage#scoped-storage

**Comment by hyjfine** [comment]
> As a workaround, you can add `android:requestLegacyExternalStorage="true"` to your `AndroidManifest.xml`'s `application` tag (it will work until Android 11)

As @Zazo032 said, i test it works. 
The workload of completing the adaptation Android 10 is relatively large, maybe doing it later.

**Comment by Zazo032** [comment]
> > As a workaround, you can add `android:requestLegacyExternalStorage="true"` to your `AndroidManifest.xml`'s `application` tag (it will work until Android 11)
> 
> As @Zazo032 said, I test it works.
> The workload of completing the adaptation Android 10 is relatively large, maybe doing it later.
> [https://developer.android.com/training/data-storage](url)

I think it may be worth to state that workaround in `README` to avoid duplicated issues
