### ISSUE TITLE
savaImage()方法，android 返回String类型，ios返回 bool类型 能统一下吗？

### ISSUE THREAD

**Issue by andyxiaoxi** [hui-z/image_gallery_saver#85]
android
 private fun saveImageToGallery(bmp: Bitmap): String {
    val context = registrar.activeContext().applicationContext
    val file = generateFile("png")
    try {
      val fos = FileOutputStream(file)
      bmp.compress(Bitmap.CompressFormat.PNG, 60, fos)
      fos.flush()
      fos.close()
      val uri = Uri.fromFile(file)
      context.sendBroadcast(Intent(Intent.ACTION_MEDIA_SCANNER_SCAN_FILE, uri))
      return uri.toString()
    } catch (e: IOException) {
      e.printStackTrace()
    }
    return ""
  }

**Comment by Moosphan** [comment]
The same problem, why this issue was closed?

**Comment by hyjfine** [comment]
any pr welcome！

**Comment by paozhuanyinyu** [comment]
可以试一下flutter_gallery_saver，返回的是String，文件的存储路径。github地址：https://github.com/paozhuanyinyu/flutter_gallery_saver
