### ISSUE TITLE
iOS模拟器调试 导入头文件image_gallery_saver/image_gallery_saver-Swift.h报错

### ISSUE THREAD

**Issue by CoderHln** [hui-z/image_gallery_saver#89]
run找不到这个头文件，重新pod install 也没作用。

**Comment by sparkmobi** [comment]
Solved the problem：

    In ImageGallerySaverPlugin.m file ,
    Replace #import "image_gallery_saver-Swift.h" with
    #import <image_gallery_saver/image_gallery_saver-Swift.h>
