### ISSUE TITLE
Execution failed for task ':image_gallery_saver:createFullJarDebug'

### ISSUE THREAD

**Issue by mrfoxie** [hui-z/image_gallery_saver#90]
I can't run my app and it's giving me error altho I tried to check whether the flutter is outdated or not but it's fine.
[![error][2]][2]
this is the last code I added in my app [link][3] 

    _save() async { if (Platform.isAndroid) { await _askPermission(); } var response = await Dio() .get(widget.imgUrl, options: Options(responseType: ResponseType.bytes)); final result = await ImageGallerySaver.saveImage(Uint8List.fromList(response.data)); print(result); Navigator.pop(context); } _askPermission() async { if (Platform.isIOS) { Map<PermissionGroup, PermissionStatus> permissions = await PermissionHandler() .requestPermissions([PermissionGroup.photos]); } else { PermissionStatus permission = await PermissionHandler() .checkPermissionStatus(PermissionGroup.storage); } }
for saving wallpaper in gallery in `Image_View.dart`.

  [2]: https://i.stack.imgur.com/I5Doz.png
  [3]: https://github.com/mrfoxie/wallpaper

**Comment by hyjfine** [comment]
check you gradle is work all right

**Comment by mrfoxie** [comment]
yes it's works fine

**Comment by m2faridi** [comment]
The gradle does not work in the latest version

**Comment by mrfoxie** [comment]
ok

**Comment by hyjfine** [comment]
> The gradle does not work in the latest version

what is the version of your gradle?

**Comment by hyjfine** [comment]
> yes it's works fine
please post your flutter doctor info. and make sure your install gradle-6.1.1-all.zip otherwise configure the build.gradle:
dependencies {
        classpath 'com.android.tools.build:gradle:x.x.x'
}
