### ISSUE TITLE
java.io.FileNotFoundException: /storage/emulated/0/link4wa/1592683732356.png (No such file or directory)

### ISSUE THREAD

**Issue by Calvin2274** [hui-z/image_gallery_saver#91]
`Future<void> _captureAndSavePng() async {
    try{
        RenderRepaintBoundary boundary = globalKey.currentContext.findRenderObject(); 
        var image = await boundary.toImage();
        ByteData byteData = await image.toByteData(format: ui.ImageByteFormat.png);
        final result = await ImageGallerySaver.saveImage(byteData.buffer.asUint8List());
        print(result);
    }
    catch(e){
      print(e.toString());
    }
  }`

W/System.err(28198): java.io.FileNotFoundException: /storage/emulated/0/link4wa/1592683732356.png (No such file or directory)
W/System.err(28198): 	at java.io.FileOutputStream.open0(Native Method)
W/System.err(28198): 	at java.io.FileOutputStream.open(FileOutputStream.java:308)
W/System.err(28198): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:238)
W/System.err(28198): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:180)
W/System.err(28198): 	at com.example.imagegallerysaver.ImageGallerySaverPlugin.saveImageToGallery(ImageGallerySaverPlugin.kt:61)
W/System.err(28198): 	at com.example.imagegallerysaver.ImageGallerySaverPlugin.onMethodCall(ImageGallerySaverPlugin.kt:33)
W/System.err(28198): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
W/System.err(28198): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
W/System.err(28198): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
W/System.err(28198): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(28198): 	at android.os.MessageQueue.next(MessageQueue.java:326)
W/System.err(28198): 	at android.os.Looper.loop(Looper.java:160)
W/System.err(28198): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
W/System.err(28198): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(28198): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
W/System.err(28198): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by hyjfine** [comment]
please upgrade latest version and check.

**Comment by hyjfine** [comment]
#63
