### ISSUE TITLE
PNG Bytes automatically converted to jpg

### ISSUE THREAD

**Issue by doublecookie** [hui-z/image_gallery_saver#93]
Im following the example code for screen capture and getting the png bytes in app.
But ImageGallerySaver seems to always convert these to jpg.
Is there any way to change this behaviour?

**Comment by hyjfine** [comment]
ImageGallerySaver.saveImage api implement change quality，so use jpg
in you case maybe try ImageGallerySaver.saveFile api

**Comment by doublecookie** [comment]
Thankyou, saving the bytes as files and then resaving with ImageGallerySaver.saveFile() works great!
