### ISSUE TITLE
Rename folder

### ISSUE THREAD

**Issue by cesarramirez1912** [hui-z/image_gallery_saver#94]
how to rename the folder when using RenderRepaintBoundary to save image ?

"/storage/emulated/0/THIS_FOLDER/teste.jpg"

**Comment by ashleymooney123** [comment]
This is what I did and it seemed to work !

_saveScreen() async {
    String folderMain = "NewFolder";
    RenderRepaintBoundary boundary = previewContainer.currentContext.findRenderObject();
    ui.Image image = await boundary.toImage();
    ByteData byteData = await image.toByteData(format: ui.ImageByteFormat.png);
    debugPrint("$ByteData");
    final result = await ImageGallerySaver.saveImage(
    byteData.buffer.asUint8List());
    print(result);
  }
