### ISSUE TITLE
Image Gallery Saver 1.5.0   error: 'jpegData(compressionQuality:)' has been renamed to 'UIImageJPEGRepresentation(_:_:)'

### ISSUE THREAD

**Issue by ashleymooney123** [hui-z/image_gallery_saver#96]
ERROR:

Xcode's output:
↳
 error: 'jpegData(compressionQuality:)' has been renamed to 'UIImageJPEGRepresentation(_:_:)'
            let newImage = image.jpegData(compressionQuality: CGFloat(quality / 100))!
                                 ^~~~~~~~
                                 UIImageJPEGRepresentation
    UIKit.UIImage:60:17: note: 'jpegData(compressionQuality:)' was introduced in Swift 4.2
        public func jpegData(compressionQuality: CGFloat) -> Data?
                    ^

SIMILAR ISSUE:
https://github.com/ko2ic/image_downloader/issues/33

This issue was fixed in the forum above by :
1.  project was initially created with kotlin and swift ...
Fixed issue by creating new project with classical stuff java and objc and it works.

Wondering if i what to code my project in java & obj C 

Thanks in advance,
Ashley

**Comment by MATTYGILO** [comment]
i'm having the same issue

**Comment by ashleymooney123** [comment]
https://github.com/hui-z/image_gallery_saver/issues/24

I followed this and it works

**Comment by uzumakinaruto123** [comment]
@xqqlv  @ashleymooney123 Still facing this on latest version 1.6.9 in a swift project.  The above steps don't work.
