### ISSUE TITLE
iOS正常，Android并没有存到相册

### ISSUE THREAD

**Issue by zhuwei** [hui-z/image_gallery_saver#97]
Android返回的是存储路径，但这并不是相册
`file:///storage/emulated/0/XXXXXX/1594979330535.jpg`

我代码写的有问题？

**Comment by yanzhuang0623** [comment]
我也遇到了这个问题

**Comment by hyjfine** [comment]
maybe you should refresh media:


 `private fun refreshMedia(filePath: String, isImage: Boolean = true) {
        context?.let {

                MediaStore.Images.Media.insertImage(
                    it.applicationContext.contentResolver,
                    filePath,
                    "name",
                    "description"
                )

            it.applicationContext.sendBroadcast(
                Intent(
                    Intent.ACTION_MEDIA_SCANNER_SCAN_FILE,
                    Uri.fromFile(File(filePath))
                )
            )
        }
    }`
